### ISSUE TITLE
[Pager] IllegalStateException when quickly scrolling pages in HorizontalPager

### ISSUE THREAD

**Issue by miduch** [google/accompanist#1009]
**Description**
Following crash happens when pages are dragged a bit quickly 

compose version:  1.2.0-alpha03
accompanist version:  0.24.2-alpha

2022-02-11 11:16:40.313 16888-16888/com.example.horizontalpager E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.horizontalpager, PID: 16888
    java.lang.IllegalStateException: Check failed.
        at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$precompose$1.dispose(SubcomposeLayout.kt:566)
        at androidx.compose.foundation.lazy.layout.LazyLayoutPrefetcher.cancelScheduledPrefetch(LazyLayoutPrefetcher.android.kt:274)
        at androidx.compose.foundation.lazy.layout.LazyLayoutPrefetchPolicy.cancelScheduledPrefetch(LazyLayoutPrefetchPolicy.kt:42)
        at androidx.compose.foundation.lazy.LazyListState.notifyPrefetch(LazyListState.kt:305)
        at androidx.compose.foundation.lazy.LazyListState.onScroll$foundation_release(LazyListState.kt:266)
        at androidx.compose.foundation.lazy.LazyListState$scrollableState$1.invoke(LazyListState.kt:150)
        at androidx.compose.foundation.lazy.LazyListState$scrollableState$1.invoke(LazyListState.kt:150)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scrollScope$1.scrollBy(ScrollableState.kt:134)
        at androidx.compose.foundation.gestures.ScrollingLogic.dispatchScroll-f0eR0lY(Scrollable.kt:314)
        at androidx.compose.foundation.gestures.ScrollDraggableState.dragBy-Uv8p0NA(Scrollable.kt:389)
        at androidx.compose.foundation.gestures.DraggableKt$draggable$9$2$2.invokeSuspend(Draggable.kt:244)
        at androidx.compose.foundation.gestures.DraggableKt$draggable$9$2$2.invoke(Unknown Source:8)
        at androidx.compose.foundation.gestures.DraggableKt$draggable$9$2$2.invoke(Unknown Source:4)
        at androidx.compose.foundation.gestures.ScrollDraggableState$drag$2.invokeSuspend(Scrollable.kt:400)
        at androidx.compose.foundation.gestures.ScrollDraggableState$drag$2.invoke(Unknown Source:8)
        at androidx.compose.foundation.gestures.ScrollDraggableState$drag$2.invoke(Unknown Source:4)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invokeSuspend(ScrollableState.kt:148)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invoke(Unknown Source:8)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invoke(Unknown Source:4)
        at androidx.compose.foundation.MutatorMutex$mutateWith$2.invokeSuspend(MutatorMutex.kt:160)
        at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke(Unknown Source:8)
        at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
        at androidx.compose.foundation.MutatorMutex.mutateWith(MutatorMutex.kt:153)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invokeSuspend(ScrollableState.kt:145)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invoke(Unknown Source:8)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
        at androidx.compose.foundation.gestures.DefaultScrollableState.scroll(ScrollableState.kt:144)
        at androidx.compose.foundation.lazy.LazyListState.scroll(LazyListState.kt:235)
        at androidx.compose.foundation.gestures.ScrollDraggableState.drag(Scrollable.kt:398)
        at androidx.compose.foundation.gestures.DraggableKt$draggable$9$2.invokeSuspend(Draggable.kt:241)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:68)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
2022-02-11 11:16:40.314 16888-16888/com.example.horizontalpager E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:845)
        at android.view.Choreographer.doFrame(Choreographer.java:775)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Steps to reproduce**
Create HorizontalPager with some items in it and start swiping quickly (on device/ Pixel 6 in mycase). after a while app will crash

val pagerState = rememberPagerState()
val pages = listOf("Page 1", "Page 2", "Page 3", "Page 4")

HorizontalPager(
            count = pages.size,
            state = pagerState,
            key = { page -> pages[page].hashCode() }
        ) { page ->
            Text(
                modifier = Modifier
                    .size(400.dp)
                    .background(Color.Yellow),
                text = "Hello ${pages[page]}"
            )
        }

**Expected behavior** 
No crash happens 

**Additional context**

Works fine with following versions 

compose version:  1.1.0
accompanist version:  0.23.0

**Comment by andkulikov** [comment]
Thanks for reporting. We track this issue in this bug - https://issuetracker.google.com/issues/218668336

**Comment by AzizbekRasulmetov** [comment]
The same error I am facing now, It is crashing suddenly when i swipe between pages

**Comment by andkulikov** [comment]
It will be fixed in Compose 1.2.0-alpha04. please use previous versions for now

**Comment by alicse233** [comment]
@andkulikov tried version:
0.15.0
still, the app is crashing on a fast scroll and normal scroll once the total number of pages are swiped and I start scrolling again it just crashes the app.

**Comment by andkulikov** [comment]
0.15 is very old. you can now use the latest version of accompanist and manually specifying compose 1.2.0-alpha04

**Comment by YusufbekIbragimov** [comment]
I use compose 1.2.1 version and I should which version of pager? I have still  this bug

**Comment by andkulikov** [comment]
It should work with 1.2.1. Could you please show the stacktrace of the crash you get?

**Comment by Rissmon** [comment]
@andkulikov Here is the stacktrace I got
```
Exception java.lang.IllegalArgumentException:
  at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose (SubcomposeLayout.kt:411)
  at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose (SubcomposeLayout.kt:732)
  at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw (LazyLayoutMeasureScope.kt:118)
  at androidx.compose.foundation.lazy.LazyMeasuredItemProvider.getAndMeasure-ZjPyQlc (LazyMeasuredItemProvider.kt:47)
  at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-7Xnphek (LazyListMeasure.kt:151)
  at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke-0kLqBqw (LazyList.kt:304)
  at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke (LazyList.kt:197)
  at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$2$1.invoke-0kLqBqw (LazyLayout.kt:74)
  at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$2$1.invoke (LazyLayout.kt:70)
  at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s (SubcomposeLayout.kt:590)
  at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0 (InnerPlaceable.kt:44)
  at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s (GraphicsLayerModifier.kt:405)
  at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0 (ModifiedLayoutNode.kt:53)
  at androidx.compose.foundation.layout.PaddingModifier.measure-3p2s80s (Padding.kt:364)
  at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0 (ModifiedLayoutNode.kt:53)
  at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke (LayoutNode.kt:1428)
  at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke (LayoutNode.kt:1427)
  at androidx.compose.runtime.snapshots.Snapshot$Companion.observe (Snapshot.kt:2116)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads (SnapshotStateObserver.kt:110)
  at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release (OwnerSnapshotObserver.kt:78)
  at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release (OwnerSnapshotObserver.kt:66)
  at androidx.compose.ui.node.LayoutNode.performMeasure-BRTryo0$ui_release (LayoutNode.kt:1427)
  at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0 (OuterMeasurablePlaceable.kt:94)
  at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release (LayoutNode.kt:1381)
  at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default (LayoutNode.kt:1372)
  at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA (MeasureAndLayoutDelegate.kt:187)
  at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded (MeasureAndLayoutDelegate.kt:274)
  at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtree (MeasureAndLayoutDelegate.kt:317)
  at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtree (MeasureAndLayoutDelegate.kt:325)
  at androidx.compose.ui.platform.AndroidComposeView.forceMeasureTheSubtree (AndroidComposeView.android.kt:773)
  at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0 (OuterMeasurablePlaceable.kt:106)
  at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0 (OuterMeasurablePlaceable.kt:75)
  at androidx.compose.ui.node.LayoutNode.measure-BRTryo0 (LayoutNode.kt:1366)
  at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasurePolicy$1.measure-3p2s80s (RowColumnImpl.kt:89)
  at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0 (InnerPlaceable.kt:44)
  at androidx.compose.foundation.ScrollingLayoutModifier.measure-3p2s80s (Scroll.kt:345)
  at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0 (ModifiedLayoutNode.kt:53)
  at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s (GraphicsLayerModifier.kt:405)
  at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0 (ModifiedLayoutNode.kt:53)
  at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke (LayoutNode.kt:1428)
  at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke (LayoutNode.kt:1427)
  at androidx.compose.runtime.snapshots.Snapshot$Companion.observe (Snapshot.kt:2116)
  at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads (SnapshotStateObserver.kt:110)
  at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release (OwnerSnapshotObserver.kt:78)
  at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release (OwnerSnapshotObserver.kt:66)
  at androidx.compose.ui.node.LayoutNode.performMeasure-BRTryo0$ui_release (LayoutNode.kt:1427)
  at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0 (OuterMeasurablePlaceable.kt:94)
  at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release (LayoutNode.kt:1381)
  at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default (LayoutNode.kt:1372)
  at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA (MeasureAndLayoutDelegate.kt:187)
  at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded (MeasureAndLayoutDelegate.kt:274)
  at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$remeasureAndRelayoutIfNeeded (MeasureAndLayoutDelegate.kt:38)
  at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout (MeasureAndLayoutDelegate.kt:208)
  at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout (AndroidComposeView.android.kt:757)
  at androidx.compose.ui.node.Owner$-CC.measureAndLayout$default (Owner.kt:196)
  at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw (AndroidComposeView.android.kt:954)
  at android.view.View.draw (View.java:22521)
  at android.view.View.updateDisplayListIfDirty (View.java:21386)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:4524)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:4497)
  at android.view.View.updateDisplayListIfDirty (View.java:21346)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:4524)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:4497)
  at android.view.View.updateDisplayListIfDirty (View.java:21346)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:4524)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:4497)
  at android.view.View.updateDisplayListIfDirty (View.java:21346)
  at android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:4524)
  at android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:4497)
  at android.view.View.updateDisplayListIfDirty (View.java:21346)
  at android.view.ThreadedRenderer.updateViewTreeDisplayList (ThreadedRenderer.java:559)
  at android.view.ThreadedRenderer.updateRootDisplayList (ThreadedRenderer.java:565)
  at android.view.ThreadedRenderer.draw (ThreadedRenderer.java:642)
  at android.view.ViewRootImpl.draw (ViewRootImpl.java:4232)
  at android.view.ViewRootImpl.performDraw (ViewRootImpl.java:3946)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:3217)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2057)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:8362)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1058)
  at android.view.Choreographer.doCallbacks (Choreographer.java:880)
  at android.view.Choreographer.doFrame (Choreographer.java:813)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1043)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:236)
  at android.app.ActivityThread.main (ActivityThread.java:7861)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:600)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:967)
```

**Comment by andkulikov** [comment]
@Rissmon This crash happens when multiple items of the list have the same key. Please check what keys do you provide for your items and that the keys are always unique
