### ISSUE TITLE
[Navigation] Navigation animation experience is very poor

### ISSUE THREAD

**Issue by gaohomway** [google/accompanist#1019]
**Description**

For bottom bar switching and regular navigation, I'm using navigation animations. [demo](https://www.youtube.com/watch?v=_2SB_Mzb79A)

**Steps to reproduce**

Expansion NavGraphBuilder.composable

```
@OptIn(ExperimentalAnimationApi::class)
fun NavGraphBuilder.composable(route: String, arguments: List<NamedNavArgument> = emptyList(), content: @Composable (NavBackStackEntry) -> Unit) {

    val enterTransition: AnimatedContentScope<NavBackStackEntry>.() -> EnterTransition? = {
        slideIntoContainer(AnimatedContentScope.SlideDirection.Left, tween(400))
    }
    val exitTransition: AnimatedContentScope<NavBackStackEntry>.() -> ExitTransition? = {
        slideOutOfContainer(AnimatedContentScope.SlideDirection.Left, tween(400))
    }

    val popEnterTransition: AnimatedContentScope<NavBackStackEntry>.() -> EnterTransition? = {
        slideIntoContainer(AnimatedContentScope.SlideDirection.Right, tween(350))
    }
    val popExitTransition: AnimatedContentScope<NavBackStackEntry>.() -> ExitTransition? = {
        slideOutOfContainer(AnimatedContentScope.SlideDirection.Right, tween(300))
    }

    composable(route = route,
        enterTransition = enterTransition, popEnterTransition = popEnterTransition,
        popExitTransition = popExitTransition, exitTransition = exitTransition) { stack ->
        content(stack)
    }
}

```

Extension for bottom bar NavGraphBuilder.composableBottomBar

```
@OptIn(ExperimentalAnimationApi::class)
fun NavGraphBuilder.composableBottomBar(route: String, content: @Composable (NavBackStackEntry) -> Unit) {

    val enterTransition: AnimatedContentScope<NavBackStackEntry>.() -> EnterTransition? = {
        println("enterTransition")
        slideIntoContainer(AnimatedContentScope.SlideDirection.Left, tween(0))
    }
    val popExitTransition: AnimatedContentScope<NavBackStackEntry>.() -> ExitTransition? = {
        val iR = initialState.destination.route
        val tR = targetState.destination.route

        if ((iR == "contactView" && tR == "homeView") || (iR == "myView" && tR == "homeView") || (iR == "exploreView" && tR == "homeView")) {
            null
        }else{
            slideOutOfContainer(AnimatedContentScope.SlideDirection.Right, tween(0))
        }
    }

    val popEnterTransition: AnimatedContentScope<NavBackStackEntry>.() -> EnterTransition? = {
        val iR = initialState.destination.route
        val tR = targetState.destination.route

        // 从 initialState 到 targetState
        if ((iR == "contactView" && tR == "homeView") || (iR == "myView" && tR == "homeView") || (iR == "exploreView" && tR == "homeView")) {
            null
        }else{
            slideIntoContainer(AnimatedContentScope.SlideDirection.Right, tween(250))
        }
    }
    val exitTransition: AnimatedContentScope<NavBackStackEntry>.() -> ExitTransition? = {
        val iR = initialState.destination.route
        val tR = targetState.destination.route

        if ((iR == "contactView" && tR == "exploreView") || (iR == "exploreView" && tR == "contactView")) {
            null
        }else if ((iR == "contactView" && tR == "myView") || iR == "myView" && tR == "contactView") {
            null
        }else if ((iR == "exploreView" && tR == "myView") || iR == "myView" && tR == "exploreView") {
            null
        }else{
            slideOutOfContainer(AnimatedContentScope.SlideDirection.Left, tween(600))
        }
    }

    composable(route = route,
        enterTransition = enterTransition, popEnterTransition = popEnterTransition,
        popExitTransition = popExitTransition, exitTransition = exitTransition) { stack ->
        content(stack)
    }
}
```
**problem**

1. It is very complicated to use, and various judgments need to be made according to `initialState` and `targetState`
2. When the animation is empty, there is still a transition animation, but it is very small and feels very sticky. sometimes no animation. very strange question.

**Expected behavior** 

**Additional context**

**Comment by jbw0033** [comment]
This is kind of the best way you can have complete control of the animations in the system, it just comes with the overhead of defining them ahead of time. 

Trying to do that all as part of a single extension function is probably more confusing than letting each composable define its own animation relationships.

You can set defaults at the graph level by setting them on `NavHost()` or `navigation()` calls. Using `EnterAnimation.None` or `ExitAnimation.None` makes it easy to clear the default animation.

But in general, yes the more custom things you do the more things you will need to define yourself.

**Comment by gaohomway** [comment]
Passing `EnterAnimation.None` and `ExitAnimation.None` does eliminate the animation, but introduces new problems.
Switching between pages, crashes randomly, reporting the following error:

Is it caused by `EnterAnimation.None` and `ExitAnimation.None`?

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.feifeng, PID: 9321
    java.lang.IllegalStateException: You cannot access the NavBackStackEntry's ViewModels after the NavBackStackEntry is destroyed.
        at androidx.navigation.NavBackStackEntry.getViewModelStore(NavBackStackEntry.kt:207)
        at androidx.lifecycle.ViewModelProvider.<init>(ViewModelProvider.kt:102)
        at androidx.lifecycle.viewmodel.compose.ViewModelKt.get(ViewModel.kt:82)
        at androidx.lifecycle.viewmodel.compose.ViewModelKt.viewModel(ViewModel.kt:72)
        at com.feifeng.contact.ContactsViewKt.ContactContent(ContactsView.kt:128)
        at com.feifeng.contact.ContactsViewKt$ContactView$2.invoke(ContactsView.kt:48)
        at com.feifeng.contact.ContactsViewKt$ContactView$2.invoke(ContactsView.kt:47)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
        at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
        at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:157)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2270)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2530)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3038)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3024)
        at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:247)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3024)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2999)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:709)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:876)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:107)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:485)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:454)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
        at android.view.Choreographer.doCallbacks(Choreographer.java:845)
        at android.view.Choreographer.doFrame(Choreographer.java:775)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/Process: Sending signal. PID: 9321 SIG: 9


```

**Comment by Radiokot** [comment]
I litteraly experience this 3 years later in 2.8.8
