### ISSUE TITLE
[Pager] IllegalStateException with Snapshot at fragment start

### ISSUE THREAD

**Issue by HugoAlberto** [google/accompanist#1068]
Hi,

**Description**
When my fragment starts, it sometimes (around 1/7 chances I'd say) crashes right away with this exception : 
```
java.lang.IllegalStateException: Reading a state that was created after the snapshot was taken or in a snapshot that has not yet been applied
        at androidx.compose.runtime.snapshots.SnapshotKt.readError(Snapshot.kt:1527)
        at androidx.compose.runtime.snapshots.SnapshotKt.current(Snapshot.kt:1770)
        at androidx.compose.runtime.SnapshotMutableStateImpl.setValue(SnapshotState.kt:299)
        at com.google.accompanist.pager.PagerState.setFlingAnimationTarget$pager_release(PagerState.kt:376)
        at com.google.accompanist.pager.Pager.Pager-05tvjtU(Pager.kt:238)
        at com.google.accompanist.pager.Pager.HorizontalPager-Fsagccs(Pager.kt:151)
        at <my-app-package>.PagerFragment.SetContent(ModeLinePagerFragment.kt:121)
```

My Fragment does not have any specific logic : 
```
....
@Composable
fun SetContent() {
        val viewState by viewModel.state.collectAsState()

        HorizontalPager( <<-------------------------------- Crash at this line
            state = viewState.pagerState,
            count = viewState.tabs.count()
        ) { page ->
            val pageItem = viewState.tabs[page]
            ....
```
At this moment, state is `PagerState(currentPage = 0)` and count is `0`, as the layout is being fetched.

Edit : 
Accompanist version : 0.23.0
Compose version : 1.1.1
AndroidX Fragment version : 1.3.6

Thanks !

**Comment by andkulikov** [comment]
Hey! Do you also use Modifier.pagerTabIndicatorOffset() or read PagerState.targetPage somewhere?
