### ISSUE TITLE
[Navigation] You cannot access the NavBackStackEntry's ViewModels after the NavBackStackEntry is destroyed.

### ISSUE THREAD

**Issue by gaohomway** [google/accompanist#1079]
**Version：**

```
    implementation 'com.google.accompanist:accompanist-navigation-material:0.24.2-alpha'
    implementation 'com.google.accompanist:accompanist-navigation-animation:0.24.2-alpha'
```

**Navigation animation：**
```
    val enterTransition: AnimatedContentScope<NavBackStackEntry>.() -> EnterTransition? = {
        slideIntoContainer(AnimatedContentScope.SlideDirection.Left, tween(400))
    }
    val exitTransition: AnimatedContentScope<NavBackStackEntry>.() -> ExitTransition? = {
        slideOutOfContainer(AnimatedContentScope.SlideDirection.Left, tween(900))
    }

    val popEnterTransition: AnimatedContentScope<NavBackStackEntry>.() -> EnterTransition? = {
        slideIntoContainer(AnimatedContentScope.SlideDirection.Right, tween(150))
    }
    val popExitTransition: AnimatedContentScope<NavBackStackEntry>.() -> ExitTransition? = {
        slideOutOfContainer(AnimatedContentScope.SlideDirection.Right, tween(400))
    }
```

**FavoriteView.kt**

```
@Composable
fun FavoriteView(navController: NavController) {

    val scrollBehavior = remember { TopAppBarDefaults.pinnedScrollBehavior() }

    Scaffold(
        modifier = Modifier.nestedScroll(scrollBehavior.nestedScrollConnection),
        topBar = {
            TopAppBar(title = R.string.favorite, scrollBehavior = scrollBehavior) {
                navController.popBackStack()
            }
        },
        content = { FavoriteContent(navController) }
    )
}


@Composable
fun FavoriteContent(navController: NavController, viewModel : WindViewModel = viewModel()) {

    // ...
}

```

**Error**

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.feifeng, PID: 15120
    java.lang.IllegalStateException: You cannot access the NavBackStackEntry's ViewModels after the NavBackStackEntry is destroyed.
        at androidx.navigation.NavBackStackEntry.getViewModelStore(NavBackStackEntry.kt:205)
        at androidx.lifecycle.viewmodel.compose.ViewModelKt.get(ViewModel.kt:208)
        at androidx.lifecycle.viewmodel.compose.ViewModelKt.viewModel(ViewModel.kt:156)
        at com.feifeng.my.FavoriteViewKt.FavoriteContent(FavoriteView.kt:101)
        at com.feifeng.my.FavoriteViewKt$FavoriteView$2.invoke(FavoriteView.kt:44)
        at com.feifeng.my.FavoriteViewKt$FavoriteView$2.invoke(FavoriteView.kt:44)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
        at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
        at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:157)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2270)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2530)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3038)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3024)
        at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:252)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3024)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2999)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:709)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:876)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:107)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:485)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:454)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1074)
        at android.view.Choreographer.doCallbacks(Choreographer.java:897)
        at android.view.Choreographer.doFrame(Choreographer.java:822)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8060)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
D/OOMEventManagerFK: checkEventAndDumpForJE: 0
I/Process: Sending signal. PID: 15120 SIG: 9

```

Is it a problem of use, or a problem of Navigation?

**Comment by lutobler** [comment]
I have the same problem. For me this occurs when navigating between two components using the bottom bar, and both components use their route's BackStackEntry as a ViewModelStoreOwner. It occurs for me when tapping back and forth between the views quite fast, so when the transition animation is still running.

**Comment by trevjonez** [comment]
Seem that the likely root cause is with the integration between the androidx navigation and lifecycle libraries.

https://issuetracker.google.com/issues/228865698

**Comment by josh-Muleshi** [comment]
can you change the NavController to NavHostController ?

**Comment by svenjacobs** [comment]
I got the same crash in Crashlytics from a customer but cannot reproduce it. Is there a fix for this?

Compose: `1.3.1` (BOM `2023.01.00`)
Accompanist: `0.28.0`
Jetpack Navigation: `2.5.3`

**Comment by TheNephilim88** [comment]
Same here, but still cant reproduce on my own :(

**Comment by James-Aidoo** [comment]
Same here. Reproducing it is the problem. Seems impossible

**Comment by Minoro75** [comment]
after setting animation duration scale in Developer Options of device - crash reproduces every time.
