### ISSUE TITLE
[System UI Controller] Introducing this library make app crash

### ISSUE THREAD

**Issue by ag2s20150909** [google/accompanist#1139]
**Description**
Introducing this library will caused app crash When scrolling  LazyColumn，even if it is not used in the current @Composable fun
**Steps to reproduce**
compose_version = '1.1.1'
implementation 'com.google.accompanist:accompanist-systemuicontroller:0.24.7-alpha'

**Expected behavior** 

**Additional context**

```
java.lang.IllegalArgumentException: Inconsistency between the count of nodes tracked by the state (0) and the children count on the SubcomposeLayout (1). Are you trying to use the state of the disposed SubcomposeLayout?
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.makeSureStateIsConsistent(SubcomposeLayout.kt:514)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:391)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:715)
	at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1$1.invoke-0kLqBqw(BoxWithConstraints.kt:66)
	at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1$1.invoke(BoxWithConstraints.kt:64)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:581)
	at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:44)
	at androidx.compose.foundation.layout.SizeModifier.measure-3p2s80s(Size.kt:781)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1388)
	at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1387)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2063)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:112)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:66)
	at androidx.compose.ui.node.LayoutNode.performMeasure-BRTryo0$ui_release(LayoutNode.kt:1387)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:94)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:1341)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default(LayoutNode.kt:1337)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:187)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:274)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:38)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:208)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:740)
	at androidx.compose.ui.node.Owner$DefaultImpls.measureAndLayout$default(Owner.kt:196)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:937)
	at android.view.View.draw(View.java:22002)
	at android.view.View.updateDisplayListIfDirty(View.java:20859)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
	at android.view.View.updateDisplayListIfDirty(View.java:20817)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
	at android.view.View.updateDisplayListIfDirty(View.java:20817)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
	at android.view.View.updateDisplayListIfDirty(View.java:20817)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
	at android.view.View.updateDisplayListIfDirty(View.java:20817)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:583)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:589)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4317)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4125)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3385)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
	at android.view.Choreographer.doFrame(Choreographer.java:911)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

**Comment by ag2s20150909** [comment]
https://github.com/google/accompanist/issues/1136
