### ISSUE TITLE
[Pager] project build failed when useing version  0.24.7-alpha, other version is fine 

### ISSUE THREAD

**Issue by tongfuzz** [google/accompanist#1149]
**Description**
 ### project build failed after import  pager:0.24.7-alpha,   I have tried the other versions is good
 AndroidStudio Version :  Android Studio Bumblebee | 2021.1.1 Patch 3  
 Compose Version : 1.2.0-alpha07
 Gradle Version : 7.2
 Gradle Plugin Version : 7.1.3
 Kotlin Version : 1.6.10

 error log:  

> The root cause java.lang.RuntimeException was thrown at: org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:50)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException(CodegenUtil.kt:239)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException$default(CodegenUtil.kt:235)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invokeSequential(performByIrFile.kt:68)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invoke(performByIrFile.kt:55)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invoke(performByIrFile.kt:41)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:29)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:29)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:43)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.doGenerateFilesInternal(JvmIrCodegenFactory.kt:195)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.generateModule(JvmIrCodegenFactory.kt:60)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:331)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:123)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:434)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:120)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:357)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally$default(IncrementalCompilerRunner.kt:299)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl$rebuild(IncrementalCompilerRunner.kt:118)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:169)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:80)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:622)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:100)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1713)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Exception while generating code for:
FUN name:XimalayaApp visibility:public modality:FINAL <> ($composer:androidx.compose.runtime.Composer?, $changed:kotlin.Int) returnType:kotlin.Unit
  annotations:
    Composable
    ComposableTarget(applier = 'androidx.compose.ui.UiComposable')
  VALUE_PARAMETER name:$composer index:0 type:androidx.compose.runtime.Composer? [assignable]
  VALUE_PARAMETER name:$changed index:1 type:kotlin.Int
  BLOCK_BODY
    WHEN type=kotlin.Unit origin=IF
      BRANCH
        if: CALL 'public final fun isTraceInProgress (): kotlin.Boolean declared in androidx.compose.runtime.ComposerKt' type=kotlin.Boolean origin=null
        then: CALL 'public final fun traceEventStart (key: kotlin.Int, dirty1: kotlin.Int, dirty2: kotlin.Int, info: kotlin.String): kotlin.Unit declared in androidx.compose.runtime.ComposerKt' type=kotlin.Unit origin=null
          key: CONST Int type=kotlin.Int value=2059246336
          dirty1: CONST String type=kotlin.String value="com.tongfu.ximalaya.XimalayaApp (XimalayaApp.kt:30)"
    BLOCK type=kotlin.Unit origin=null
      SET_VAR '$composer: androidx.compose.runtime.Composer? [assignable] declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp' type=kotlin.Unit origin=null
        CALL 'public abstract fun startRestartGroup (key: kotlin.Int): androidx.compose.runtime.Composer declared in androidx.compose.runtime.Composer' type=androidx.compose.runtime.Composer origin=null
          $this: GET_VAR '$composer: androidx.compose.runtime.Composer? [assignable] declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp' type=androidx.compose.runtime.Composer? origin=null
          key: CONST Int type=kotlin.Int value=2059246336
      CALL 'public final fun sourceInformation (composer: androidx.compose.runtime.Composer, sourceInformation: kotlin.String): kotlin.Unit declared in androidx.compose.runtime.ComposerKt' type=kotlin.Unit origin=null
        composer: GET_VAR '$composer: androidx.compose.runtime.Composer? [assignable] declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp' type=androidx.compose.runtime.Composer? origin=null
        sourceInformation: CONST String type=kotlin.String value="C(XimalayaApp)31@936L388:XimalayaApp.kt#qhgaao"
    WHEN type=kotlin.Unit origin=IF
      BRANCH
        if: CALL 'public final fun OROR (arg0: kotlin.Boolean, arg1: kotlin.Boolean): kotlin.Boolean declared in kotlin.internal.ir' type=kotlin.Boolean origin=null
          arg0: CALL 'public final fun not (): kotlin.Boolean [operator] declared in kotlin.Boolean' type=kotlin.Boolean origin=null
            $this: CALL 'public final fun EQEQEQ (arg0: kotlin.Any?, arg1: kotlin.Any?): kotlin.Boolean declared in kotlin.internal.ir' type=kotlin.Boolean origin=null
              arg0: GET_VAR '$changed: kotlin.Int declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp' type=kotlin.Int origin=null
              arg1: CONST Int type=kotlin.Int value=0
          arg1: CALL 'public final fun not (): kotlin.Boolean [operator] declared in kotlin.Boolean' type=kotlin.Boolean origin=null
            $this: CALL 'public abstract fun <get-skipping> (): kotlin.Boolean declared in androidx.compose.runtime.Composer' type=kotlin.Boolean origin=null
              $this: GET_VAR '$composer: androidx.compose.runtime.Composer? [assignable] declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp' type=androidx.compose.runtime.Composer? origin=null
        then: BLOCK type=kotlin.Unit origin=null
          CALL 'public final fun Ximalaya_composeTheme (darkTheme: kotlin.Boolean, content: kotlin.Function2<androidx.compose.runtime.Composer, kotlin.Int, kotlin.Unit>, $composer: androidx.compose.runtime.Composer?, $changed: kotlin.Int, $default: kotlin.Int): kotlin.Unit declared in com.tongfu.ximalaya.ui.theme.ThemeKt' type=kotlin.Unit origin=null
            darkTheme: COMPOSITE type=kotlin.Boolean origin=DEFAULT_VALUE
              CONST Boolean type=kotlin.Boolean value=false
            content: CALL 'internal final fun <get-lambda-1> (): kotlin.Function2<androidx.compose.runtime.Composer, kotlin.Int, kotlin.Unit> declared in com.tongfu.ximalaya.ComposableSingletons$XimalayaAppKt' type=kotlin.Function2<androidx.compose.runtime.Composer, kotlin.Int, kotlin.Unit> origin=null
              $this: GET_FIELD 'FIELD FIELD_FOR_OBJECT_INSTANCE name:INSTANCE type:com.tongfu.ximalaya.ComposableSingletons$XimalayaAppKt visibility:public [final,static]' type=com.tongfu.ximalaya.ComposableSingletons$XimalayaAppKt origin=null
            $composer: GET_VAR '$composer: androidx.compose.runtime.Composer? [assignable] declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp' type=androidx.compose.runtime.Composer? origin=null
            $changed: CONST Int type=kotlin.Int value=48
            $default: CONST Int type=kotlin.Int value=1
      BRANCH
        if: CONST Boolean type=kotlin.Boolean value=true
        then: CALL 'public abstract fun skipToGroupEnd (): kotlin.Unit declared in androidx.compose.runtime.Composer' type=kotlin.Unit origin=null
          $this: GET_VAR '$composer: androidx.compose.runtime.Composer? [assignable] declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp' type=androidx.compose.runtime.Composer? origin=null
    BLOCK type=kotlin.Unit origin=null
      BLOCK type=kotlin.Unit origin=SAFE_CALL
        VAR IR_TEMPORARY_VARIABLE name:tmp0_safe_receiver type:androidx.compose.runtime.ScopeUpdateScope? [val]
          CALL 'public abstract fun endRestartGroup (): androidx.compose.runtime.ScopeUpdateScope? declared in androidx.compose.runtime.Composer' type=androidx.compose.runtime.ScopeUpdateScope? origin=null
            $this: GET_VAR '$composer: androidx.compose.runtime.Composer? [assignable] declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp' type=androidx.compose.runtime.Composer? origin=null
        WHEN type=kotlin.Unit origin=IF
          BRANCH
            if: CALL 'public final fun EQEQEQ (arg0: kotlin.Any?, arg1: kotlin.Any?): kotlin.Boolean declared in kotlin.internal.ir' type=kotlin.Boolean origin=null
              arg0: GET_VAR 'val tmp0_safe_receiver: androidx.compose.runtime.ScopeUpdateScope? [val] declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp' type=androidx.compose.runtime.ScopeUpdateScope? origin=null
              arg1: CONST Null type=kotlin.Any? value=null
            then: CONST Null type=kotlin.Any? value=null
          BRANCH
            if: CONST Boolean type=kotlin.Boolean value=true
            then: CALL 'public abstract fun updateScope (block: kotlin.Function2<androidx.compose.runtime.Composer, kotlin.Int, kotlin.Unit>): kotlin.Unit declared in androidx.compose.runtime.ScopeUpdateScope' type=kotlin.Unit origin=null
              $this: GET_VAR 'val tmp0_safe_receiver: androidx.compose.runtime.ScopeUpdateScope? [val] declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp' type=androidx.compose.runtime.ScopeUpdateScope? origin=null
              block: BLOCK type=com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided> origin=null
                CLASS LAMBDA_IMPL CLASS name:<no name provided> modality:FINAL visibility:public/*package*/ superTypes:[kotlin.jvm.internal.Lambda; kotlin.jvm.functions.Function2<androidx.compose.runtime.Composer, kotlin.Int, kotlin.Unit>]
                  $this: VALUE_PARAMETER INSTANCE_RECEIVER name:<this> type:com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided>
                  CONSTRUCTOR GENERATED_MEMBER_IN_CALLABLE_REFERENCE visibility:public/*package*/ <> ($$changed:kotlin.Int) returnType:com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided> [primary]
                    VALUE_PARAMETER BOUND_VALUE_PARAMETER name:$$changed index:0 type:kotlin.Int
                    BLOCK_BODY
                      SET_FIELD 'FIELD FIELD_FOR_CAPTURED_VALUE name:$$changed type:kotlin.Int visibility:public/*package*/ [final]' type=kotlin.Unit origin=INITIALIZER_OF_FIELD_FOR_CAPTURED_VALUE
                        receiver: GET_VAR '<this>: com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided> declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided>' type=com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided> origin=null
                        value: GET_VAR '$$changed: kotlin.Int declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided>.<init>' type=kotlin.Int origin=null
                      DELEGATING_CONSTRUCTOR_CALL 'public constructor <init> (arity: kotlin.Int) declared in kotlin.jvm.internal.Lambda'
                        arity: CONST Int type=kotlin.Int value=2
                      BLOCK type=kotlin.Unit origin=null
                  FUN name:invoke visibility:public modality:FINAL <> ($this:com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided>, $composer:androidx.compose.runtime.Composer?, $force:kotlin.Int) returnType:kotlin.Unit
                    overridden:
                      public abstract fun invoke (p1: P1 of kotlin.jvm.functions.Function2, p2: P2 of kotlin.jvm.functions.Function2): R of kotlin.jvm.functions.Function2 declared in kotlin.jvm.functions.Function2
                    $this: VALUE_PARAMETER INSTANCE_RECEIVER name:<this> type:com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided>
                    VALUE_PARAMETER name:$composer index:0 type:androidx.compose.runtime.Composer?
                    VALUE_PARAMETER name:$force index:1 type:kotlin.Int
                    BLOCK_BODY
                      RETURN type=kotlin.Nothing from='public final fun invoke ($composer: androidx.compose.runtime.Composer?, $force: kotlin.Int): kotlin.Unit declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided>'
                        CALL 'public final fun XimalayaApp ($composer: androidx.compose.runtime.Composer?, $changed: kotlin.Int): kotlin.Unit declared in com.tongfu.ximalaya.XimalayaAppKt' type=kotlin.Unit origin=null
                          $composer: GET_VAR '$composer: androidx.compose.runtime.Composer? declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided>.invoke' type=androidx.compose.runtime.Composer? origin=null
                          $changed: CALL 'public final fun or (other: kotlin.Int): kotlin.Int [infix] declared in kotlin.Int' type=kotlin.Int origin=null
                            $this: GET_FIELD 'FIELD FIELD_FOR_CAPTURED_VALUE name:$$changed type:kotlin.Int visibility:public/*package*/ [final]' type=kotlin.Int origin=null
                              receiver: GET_VAR '<this>: com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided> declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided>.invoke' type=com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided> origin=null
                            other: CONST Int type=kotlin.Int value=1
                  FIELD FIELD_FOR_CAPTURED_VALUE name:$$changed type:kotlin.Int visibility:public/*package*/ [final]
                  FUN BRIDGE name:invoke visibility:public modality:OPEN <> ($this:com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided>, p1:kotlin.Any?, p2:kotlin.Any?) returnType:kotlin.Any?
                    $this: VALUE_PARAMETER INSTANCE_RECEIVER name:<this> type:com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided>
                    VALUE_PARAMETER BRIDGE name:p1 index:0 type:kotlin.Any?
                    VALUE_PARAMETER BRIDGE name:p2 index:1 type:kotlin.Any?
                    EXPRESSION_BODY
                      CALL 'public final fun invoke ($composer: androidx.compose.runtime.Composer?, $force: kotlin.Int): kotlin.Unit declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided>' type=kotlin.Unit origin=BRIDGE_DELEGATION
                        $this: GET_VAR '<this>: com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided> declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided>.invoke' type=com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided> origin=null
                        $composer: TYPE_OP type=androidx.compose.runtime.Composer origin=IMPLICIT_CAST typeOperand=androidx.compose.runtime.Composer
                          GET_VAR 'p1: kotlin.Any? declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided>.invoke' type=kotlin.Any? origin=null
                        $force: TYPE_OP type=kotlin.Int origin=IMPLICIT_CAST typeOperand=kotlin.Int
                          GET_VAR 'p2: kotlin.Any? declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided>.invoke' type=kotlin.Any? origin=null
                CONSTRUCTOR_CALL 'public/*package*/ constructor <init> ($$changed: kotlin.Int) [primary] declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided>' type=com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp.<no name provided> origin=null
                  $$changed: GET_VAR '$changed: kotlin.Int declared in com.tongfu.ximalaya.XimalayaAppKt.XimalayaApp' type=kotlin.Int origin=null
      WHEN type=kotlin.Unit origin=IF
        BRANCH
          if: CALL 'public final fun isTraceInProgress (): kotlin.Boolean declared in androidx.compose.runtime.ComposerKt' type=kotlin.Boolean origin=null
          then: CALL 'public final fun traceEventEnd (): kotlin.Unit declared in androidx.compose.runtime.ComposerKt' type=kotlin.Unit origin=null

	at org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:50)
	at org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate$default(FunctionCodegen.kt:43)
	at org.jetbrains.kotlin.backend.jvm.codegen.ClassCodegen.generateMethodNode(ClassCodegen.kt:360)
	at org.jetbrains.kotlin.backend.jvm.codegen.ClassCodegen.generateMethod(ClassCodegen.kt:377)
	at org.jetbrains.kotlin.backend.jvm.codegen.ClassCodegen.generate(ClassCodegen.kt:131)
	at org.jetbrains.kotlin.backend.jvm.JvmLowerKt$codegenPhase$1$1.lower(JvmLower.kt:304)
	at org.jetbrains.kotlin.backend.common.phaser.FileLoweringPhaseAdapter.invoke(PhaseBuilders.kt:120)
	at org.jetbrains.kotlin.backend.common.phaser.FileLoweringPhaseAdapter.invoke(PhaseBuilders.kt:116)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invokeSequential(performByIrFile.kt:65)
	... 46 more
Caused by: java.lang.IllegalArgumentException: Null argument in ExpressionCodegen for parameter VALUE_PARAMETER IR_EXTERNAL_DECLARATION_STUB name:dirty2 index:2 type:kotlin.Int
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitCall(ExpressionCodegen.kt:483)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitCall(ExpressionCodegen.kt:131)
	at org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl.accept(IrCallImpl.kt:47)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitWhen(ExpressionCodegen.kt:996)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitWhen(ExpressionCodegen.kt:131)
	at org.jetbrains.kotlin.ir.expressions.IrWhen.accept(IrWhen.kt:29)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitStatementContainer(ExpressionCodegen.kt:433)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitBlockBody(ExpressionCodegen.kt:437)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitBlockBody(ExpressionCodegen.kt:131)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBody.kt:54)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.generate(ExpressionCodegen.kt:228)
	at org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.doGenerate(FunctionCodegen.kt:122)
	at org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:48)
	... 55 more

> Execution failed for task ':app:compileDebugKotlin'

**Comment by andkulikov** [comment]
It is impossible to help without seeing what is the build error

**Comment by tongfuzz** [comment]
> 

sorry ,my bad , i have upate the comment

**Comment by andkulikov** [comment]
Accompanist 0.24.7-alpha is using Compose 1.2.0-alpha08, which requires Kotlin 1.6.20, so please try to update Kotlin
