### ISSUE TITLE
App crash using SwipeRefresh and LazyColumn

### ISSUE THREAD

**Issue by fabiel-casas** [google/accompanist#1161]
## Describe the bug
I used LazyColumn and SwipeRefresh composable views in my project but it seems they are throwing an error when a scroll event is triggered. this is the code that I'm using:

```
@Composable
fun ActivityList(
    activityState: ActivityState,
    onMatchSelected: (String) -> Unit,
    onRefreshMatchList: () -> Unit,
    onNavigateDeepLink: (NavDeepLinkRequest) -> Unit,
    onContentUrlOpen: (String) -> Unit,
) {
    val scrollState = rememberLazyListState()
    val activityHelper = remember { ActivityItemsHelper() }
    SwipeRefresh(
        state = rememberSwipeRefreshState(isRefreshing = activityState.isRefreshing.value),
        onRefresh = onRefreshMatchList,
        indicator = { state, trigger ->
            SwipeRefreshIndicator(
                state = state,
                refreshTriggerDistance = trigger,
                scale = true,
                backgroundColor = MaterialTheme.colors.surface,
                contentColor = MaterialTheme.colors.primary,
            )
        }
    ) {
        LazyColumn(
            state = scrollState,
            modifier = Modifier
                .fillMaxSize(),
            verticalArrangement = Arrangement.spacedBy(24.dp)
        ) {
            items(activityState.activityFeedList.value) {
                PickItemType(
                    activityItem = it,
                    onMatchSelected = onMatchSelected,
                    onContentUrlOpen = onContentUrlOpen,
                    activityHelper = activityHelper,
                    onNavigateDeepLink = onNavigateDeepLink
                )
            }
        }
    }
}

@Composable
fun PickItemType(
    activityItem: ActivityItem,
    onMatchSelected: (String) -> Unit,
    onContentUrlOpen: (String) -> Unit,
    activityHelper: ActivityItemsHelper,
    onNavigateDeepLink: (NavDeepLinkRequest) -> Unit
) {
    Surface(
        modifier = Modifier.fillMaxSize()
    ) {
        when (activityItem) {
            is ActivityItem.ContentCard -> {
                GenericContentItem(
                    genericContentCard = activityItem.genericContentCard,
                    onContentUrlOpen = onContentUrlOpen,
                )
            }
            is ActivityItem.MatchStatus -> {
                MatchFeedItem(
                    matchFeedActivity = activityItem.matchActivity,
                    onMatchSelected = onMatchSelected,
                    activityHelper = activityHelper,
                    onNavigateDeepLink = onNavigateDeepLink
                )
            }
        }
    }
}

data class ActivityState(
    val account: State<Account?> = mutableStateOf(null),
    val isLoadingVisible: State<Boolean> = mutableStateOf(false),
    val isRefreshing: State<Boolean> = mutableStateOf(false),
    val activityFeedList: State<List<ActivityItem>> = mutableStateOf(emptyList()),
)
```

## To Reproduce
1. Click on an item
2. Go back to the scroll screen
3. Scroll down or up
4. App crash

## Environment:
 - Android OS version: Android 12
 - Device: Galaxy S21 Ultra 5G
 - Accompanist version: 0.24.1-alpha

## Additional context
this is the log error.
```
2022-05-12 09:45:40.954 2877-2877/sport.mingle.android.test.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: sport.mingle.android.test.app, PID: 2877
    java.lang.IndexOutOfBoundsException: Index 5, size 2
        at androidx.compose.foundation.lazy.list.IntervalListKt.intervalIndexForItemIndex(IntervalList.kt:56)
        at androidx.compose.foundation.lazy.list.IntervalListKt.intervalForIndex(IntervalList.kt:52)
        at androidx.compose.foundation.lazy.list.LazyListItemsProviderImpl.getKey(LazyListItemsProviderImpl.kt:73)
        at androidx.compose.foundation.lazy.layout.LazyLayoutPlaceablesProvider.getAndMeasure-0kLqBqw(LazyMeasurePolicy.kt:56)
        at androidx.compose.foundation.lazy.layout.LazyLayoutPrefetcher.onPostMeasure(LazyLayoutPrefetcher.android.kt:274)
        at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$2.invoke-0kLqBqw(LazyLayout.kt:57)
        at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$2.invoke(LazyLayout.kt:44)
        at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:512)
        at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:55)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
        at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:306)
        at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:39)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:131)
        at androidx.compose.foundation.layout.FillModifier.measure-3p2s80s(Size.kt:658)
        at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:39)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:99)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:98)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1798)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:121)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:88)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:76)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:98)
        at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:1323)
        at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:168)
        at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout-0kLqBqw(MeasureAndLayoutDelegate.kt:208)
        at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout-0kLqBqw(AndroidComposeView.android.kt:702)
        at androidx.compose.ui.node.LayoutNode.forceRemeasure(LayoutNode.kt:1347)
        at androidx.compose.foundation.lazy.layout.LazyLayoutState.remeasure(LazyLayoutState.kt:54)
        at androidx.compose.foundation.lazy.LazyListState.onScroll$foundation_release(LazyListState.kt:245)
        at androidx.compose.foundation.lazy.LazyListState$scrollableState$1.invoke(LazyListState.kt:146)
        at androidx.compose.foundation.lazy.LazyListState$scrollableState$1.invoke(LazyListState.kt:146)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scrollScope$1.scrollBy(ScrollableState.kt:134)
2022-05-12 09:45:40.954 2877-2877/sport.mingle.android.test.app E/AndroidRuntime:     at androidx.compose.foundation.gestures.ScrollingLogic.dispatchScroll-iGfEq8s(Scrollable.kt:265)
        at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2$outerScopeScroll$1.invoke(Scrollable.kt:306)
        at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2$outerScopeScroll$1.invoke(Scrollable.kt:305)
        at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2$scope$1.scrollBy(Scrollable.kt:311)
        at androidx.compose.foundation.gestures.DefaultFlingBehavior$performFling$2.invoke(Scrollable.kt:403)
        at androidx.compose.foundation.gestures.DefaultFlingBehavior$performFling$2.invoke(Scrollable.kt:401)
        at androidx.compose.animation.core.SuspendAnimationKt.doAnimationFrame(SuspendAnimation.kt:321)
        at androidx.compose.animation.core.SuspendAnimationKt.access$doAnimationFrame(SuspendAnimation.kt:1)
        at androidx.compose.animation.core.SuspendAnimationKt$animate$9.invoke(SuspendAnimation.kt:262)
        at androidx.compose.animation.core.SuspendAnimationKt$animate$9.invoke(SuspendAnimation.kt:261)
        at androidx.compose.animation.core.SuspendAnimationKt$callWithFrameNanos$2.invoke(SuspendAnimation.kt:287)
        at androidx.compose.animation.core.SuspendAnimationKt$callWithFrameNanos$2.invoke(SuspendAnimation.kt:286)
        at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
        at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:432)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:425)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
        at android.view.Choreographer.doCallbacks(Choreographer.java:866)
        at android.view.Choreographer.doFrame(Choreographer.java:792)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by JanZeman** [comment]
I am experiencing exactly the same IndexOutOfBoundsException. Has anyone tried to look at this issue yet?

**Comment by andkulikov** [comment]
Can you please check if it works the same with the latest 0.24.10-beta?

Also how/when do you change the amount of items you have in a list? Is it really changing from the list containing at least 5 items to the list containing only 2 items?
