### ISSUE TITLE
[Pager] HorizontalPager - Looping Sample Crashing

### ISSUE THREAD

**Issue by bentrengrove** [google/accompanist#1188]
**Steps to reproduce**
Open sample

**Additional context**
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.accompanist.sample, PID: 28488
    java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter it
        at androidx.compose.foundation.lazy.LazyListItemProviderImplKt$generateKeyToIndexMap$1$1.invoke(Unknown Source:3)
        at androidx.compose.foundation.lazy.LazyListItemProviderImplKt$generateKeyToIndexMap$1$1.invoke(LazyListItemProviderImpl.kt:142)
        at androidx.compose.foundation.lazy.layout.MutableIntervalList.forEach(IntervalList.kt:153)
        at androidx.compose.foundation.lazy.LazyListItemProviderImplKt.generateKeyToIndexMap(LazyListItemProviderImpl.kt:142)
        at androidx.compose.foundation.lazy.LazyListItemsSnapshot.<init>(LazyListItemProviderImpl.kt:93)
        at androidx.compose.foundation.lazy.LazyListItemProviderImplKt$rememberItemProvider$2$1.invoke(LazyListItemProviderImpl.kt:61)
        at androidx.compose.foundation.lazy.LazyListItemProviderImplKt$rememberItemProvider$2$1.invoke(LazyListItemProviderImpl.kt:59)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2099)
        at androidx.compose.runtime.DerivedSnapshotState.currentRecord(DerivedState.kt:121)
        at androidx.compose.runtime.DerivedSnapshotState.getDependencies(DerivedState.kt:176)
        at androidx.compose.runtime.CompositionImpl.recordReadOf(Composition.kt:694)
        at androidx.compose.runtime.Recomposer$readObserverOf$1.invoke(Recomposer.kt:924)
        at androidx.compose.runtime.Recomposer$readObserverOf$1.invoke(Recomposer.kt:924)
        at androidx.compose.runtime.DerivedSnapshotState.getValue(DerivedState.kt:164)
        at androidx.compose.foundation.lazy.LazyListItemProviderImpl.getItemCount(LazyListItemProviderImpl.kt:111)
        at androidx.compose.foundation.lazy.LazyListKt.ScrollPositionUpdater(LazyList.kt:150)
        at androidx.compose.foundation.lazy.LazyListKt.LazyList(LazyList.kt:101)
        at androidx.compose.foundation.lazy.LazyDslKt.LazyRow(LazyDsl.kt:300)
        at com.google.accompanist.pager.Pager.Pager-upBTbn8(Pager.kt:419)
        at com.google.accompanist.pager.Pager.HorizontalPager-7SJ-wSw(Pager.kt:242)
        at com.google.accompanist.sample.pager.ComposableSingletons$HorizontalPagerLoopingSampleKt$lambda-6$1.invoke(HorizontalPagerLoopingSample.kt:78)
        at com.google.accompanist.sample.pager.ComposableSingletons$HorizontalPagerLoopingSampleKt$lambda-6$1.invoke(HorizontalPagerLoopingSample.kt:69)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:318)
        at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:316)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$2$1$1.invoke(SubcomposeLayout.kt:770)
        at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$2$1$1.invoke(SubcomposeLayout.kt:448)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:74)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3186)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3176)
        at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:252)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3176)
        at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3112)
```

**Comment by zwonb** [comment]
+1

**Comment by andkulikov** [comment]
We are tracking it as a Compose bug here - https://issuetracker.google.com/issues/235495226.
For now please use something like 100000 instead of Int.MAX_VALUE
