### ISSUE TITLE
Runtime error after upgrade to 1.2.0-rc01

### ISSUE THREAD

**Issue by diousk** [google/accompanist#1201]
## Describe the bug
After upgrade the compose version from 1.2.0-beta03 to 1.2.0-rc01 when I open the Activity with Compose views, the app crash with following error (1.2.0-beta03 works fine):
```
java.lang.IncompatibleClassChangeError: Found interface androidx.compose.ui.graphics.drawscope.DrawScope, but class was expected (declaration of 'androidx.compose.ui.graphics.drawscope.DrawScope' appears in /data/app/~~27Qw0QPwpprgCdqIL-Trzg==/com.sample.dev-z4txtbgvrmSbi36CKhuaCg==/base.apk)
        at androidx.compose.ui.graphics.drawscope.DrawScope.drawRect-n-J9OG0$default(DrawScope.kt:410)
        at androidx.compose.foundation.Background.drawRect(Background.kt:111)
        at androidx.compose.foundation.Background.draw(Background.kt:103)
        at androidx.compose.ui.node.DrawEntity.draw(DrawEntity.kt:98)
        at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:316)
        at androidx.compose.ui.node.LayoutNodeWrapper.access$drawContainedDrawModifiers(LayoutNodeWrapper.kt:60)
        at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:336)
        at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:335)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2101)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:110)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
        at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:335)
        at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:60)
        at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:180)
        at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:297)
        at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:238)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:301)
        at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:839)
        at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
        at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:314)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:306)
        at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:839)
        at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:960)
        at android.view.View.draw(View.java:22647)
        at android.view.View.updateDisplayListIfDirty(View.java:21519)
        at android.view.View.draw(View.java:22375)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
        at android.view.View.updateDisplayListIfDirty(View.java:21510)
        at android.view.View.draw(View.java:22375)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
        at android.view.View.updateDisplayListIfDirty(View.java:21510)
        at android.view.View.draw(View.java:22375)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
        at android.view.View.updateDisplayListIfDirty(View.java:21510)
        at android.view.View.draw(View.java:22375)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
        at android.view.View.draw(View.java:22647)
        at com.android.internal.policy.DecorView.draw(DecorView.java:820)
        at android.view.View.updateDisplayListIfDirty(View.java:21519)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4418)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4146)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3306)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
```

Here is some of my library dependency's version
```
[versions]
gradleplugin = "7.2.0"
kotlin = "1.6.21"
lifecycle = "2.4.1"
coroutines = "1.4.2"
appcompat = "1.4.1"
annotation = "1.3.0"
lottie = "5.2.0"
assent = "3.0.0-RC4"
kpermissions = "3.1.2"
compose = "1.2.0-rc01"
composecompiler = "1.2.0-rc01"
activity = "1.4.0"
coil = "2.1.0"
accompanist = "0.24.11-rc"
```

## Environment:
 - Android OS version: Android 12
 - Device: Google Pixel 3
 - Accompanist version: 0.24.11-rc

**Comment by bentrengrove** [comment]
Thanks for the report and sorry about that.

Which accompanist library are you using?

**Comment by diousk** [comment]
> Thanks for the report and sorry about that.
> 
> Which accompanist library are you using?

Hi, we're currently using
"com.google.accompanist:accompanist-pager"
"com.google.accompanist:accompanist-pager-indicators"

and the compose related dependencies:
compose = [
    "compose-ui", 
    "compose-ui-tooling", 
    "compose-foundation", 
    "compose-material", 
    "compose-foundation-layout"
]

After some experiment, I found that the app only crashes when the `Surface` composable is used, something like:
```
MaterialTheme {
    Surface { // if Surface is removed, the app would not crash
        Text(...)
    }
}
```
It seemed that the error occurred inside compose-foundation, I'' try to fire an issue there.

**Comment by siralam** [comment]
I am getting the same exception, but:

- I am not using accompanist library as I have heard it have been moved into compose.foundation;
- I am getting this runtime crash only if I enabled R8.

**Comment by bentrengrove** [comment]
Please open a bug for this at [goo.gle/compose-feedback](goo.gle/compose-feedback) as this doesn't seem related to Accompanist.

**Comment by diousk** [comment]
Hi,
It turned out that in my case it's the Applovin SDK com.applovin.quality:AppLovinQualityServiceGradlePlugin which caused the error when using with Compose 1.2.0-rc01. After I removed the applovin-quality-service plugin, the error was gone.

**Comment by TepesLucian** [comment]
Our app uses fullstory sdk gradle and i get the same crash when enabling it + R8. Seems to be an issue with compose itself not the compiler. Disabling sdk / R8 / downgrading compose (not the compiler) to `1.2.0-beta03` fixes it.

**Comment by darkharov** [comment]
still happen

id 'com.android.application' version '8.1.1' apply false
id 'com.android.library' version '8.1.1' apply false
id "org.jetbrains.kotlin.jvm" version '1.9.10' apply false
id "org.jetbrains.kotlin.android" version '1.9.10' apply false
id "com.google.devtools.ksp" version '1.9.10-1.0.13' apply false

compileSdk        : 34,
minSdk            : 26,
targetSdk         : 34,
jvmTarget         : '17',
javaVersion       : JavaVersion.VERSION_17,
kotlin            : '1.9.10',
ktxCore           : '1.12.0',
kotlinxMetadataJvm: '0.5.0',
kotlinExtension   : '1.5.3',
composeBom        : '2023.09.00',
lottieCompose     : '5.2.0',

**Comment by msusman1** [comment]
Still facing the issue 100% on the samsung Galaxy A15 Android version:14
agp = "8.8.2"
kotlin = "2.1.10"
composeBom = "2025.03.00"


androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
