### ISSUE TITLE
[Navigation Animation] navHostController not initialized when activity "started" from external intent (e.g. deep link)

### ISSUE THREAD

**Issue by alixwar** [google/accompanist#1313]
**Description**
The app crashes due to the nav controller not being available when activity is started based on a deep link intent.

**Steps to reproduce**
Pseudo code:
```kotlin
class MainActivity : ComponentActivity {

    lateinit var navHostController: NavHostController

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        
        setContentView(
            ComposeView(this).apply {
                setContent {
                    navHostController = rememberAnimatedNavController()
                    AppTheme {
                        AppNavigation(
                            navController = navHostController,
                            authViewModel = authViewModel,
                            appNavigationViewModel = appNavigationViewModel
                        )
                    }
                }
            }
        )
    }

    override fun onResume() {
        handleIntent(intent)
        super.onResume()
    }

    open fun handleIntent(intent: Intent) {
       // Code that invokes navHostController on main thread
    }

}
```

Causes:
```
Fatal Exception: kotlin.UninitializedPropertyAccessException: lateinit property navHostController has not been initialized
       at com.mycompany.MainActivity.getNavHostController(MainActivity.kt:82)
       at com.mycompany.MainActivity$handleIntent$2.invokeSuspend(MainActivity.kt:187)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
```

**Expected behavior** 
navHostController is initialized

**Additional context**
Accompanist version: 0.25.1
Compose version: 1.2.1

**Comment by alixwar** [comment]
Could it be a race condition on the main thread where both actions are happening at the same time?
- Initialization of nav controller (invoked from `onCreate()`)
- using nav controller (invoked from `onResume()`)

**Comment by Zhuinden** [comment]
You should create a `Channel<(NavController) -> Unit>` that is observed from a `LaunchedEffect(navHostController) {`, and pass your expected `handleIntent` call into that channel, so that it executes when your navHost would actually be initialized, within the Composable effect.

**Comment by Zhuinden** [comment]
I would inline that LaunchedEffect in to the callsite instead of create a separate top-level function for it as it is clearer that way, but yes

**Comment by alixwar** [comment]
Side-note: I am used to declare Effects in a separate file because of a code coverage issue: https://issuetracker.google.com/issues/209758677
