### ISSUE TITLE
[WebView] WebView causes comosables jank during loading

### ISSUE THREAD

**Issue by proninyaroslav** [google/accompanist#1362]
**Description**
Loading even a small HTML page from memory causes jank in the composable container where the WebView is located, for example, all composables in a Column have a white background until the WebView is rendered in it. I found a similar issue with Google Maps Compose https://github.com/googlemaps/android-maps-compose/issues/141

In the video, you can see that for a couple of seconds, some elements in the Column turn white, this happens at the moment when the WebView loads and renders the HTML below into this Column:

https://user-images.githubusercontent.com/7840559/193538513-a1961d84-6909-4cd3-92b7-4ee4da9d5f69.mp4

**Steps to reproduce**
1. Place WebView in any composable container (Column, Box) along with other composables
2. Load into WebView any HTML page located in memory

**Expected behavior** 
WebView must not cause jank on rendering or loading

**Comment by thekingrenz23** [comment]
did you try it on a release build

**Comment by proninyaroslav** [comment]
Yes, same problem

**Comment by proninyaroslav** [comment]
Addition: the jank happens even if I pass an empty string instead of HTML content. Changing the state again (setting real HTML) doesn't cause jank.

**Comment by bentrengrove** [comment]
There isn't much we can do to fix this in accompanist unfortunately. We do now have a workaround available with the factory parameter, you can now pass in a lambda for the creation of the webview instance. This would allow you to move the expensive view instantiation to a more convenient time in your loading.

**Comment by ln-12** [comment]
@bentrengrove what do you think of an additional accompanist lib equivalent to [AsyncLayoutInflater](https://developer.android.com/reference/androidx/asynclayoutinflater/view/AsyncLayoutInflater)? Would that be possible?

I thought that it might be possible to use the [interop API](https://developer.android.com/jetpack/compose/interop/interop-apis#fragments-in-compose) to load a fragment, which in turn loads a heavy view like a map or webview using AsyncLayoutInflater. What do you think of that approach?

**Comment by bentrengrove** [comment]
It sounds cool but it isn't something we could support in Accompanist at this time.

**Comment by bentrengrove** [comment]
Create your webview somewhere else and then something like this was what I was thinking

```
if(webView != null) {
   WebView(factory = { webView })
} else {
   Placeholder ()
}
```

**Comment by proninyaroslav** [comment]
> Create your webview somewhere else

This is probably only possible at the app start, before the Compose view is created, since any other attempts to create a WebView on the UI thread will cause rendering jank in Compose. Or maybe there are other ways?

**Comment by ln-12** [comment]
It seems like using AsyncLayoutInflater is not possible, as a webview can generally not be created on the background:
```
W/AsyncLayoutInflater: Failed to inflate resource in the background! Retrying on the UI thread
    android.view.InflateException: Binary XML file line #15 in com.example.composeasynclayout:layout/compose_view_layout: Binary XML file line #15 in com.example.composeasynclayout:layout/compose_view_layout: Error inflating class android.webkit.WebView
    Caused by: android.view.InflateException: Binary XML file line #15 in com.example.composeasynclayout:layout/compose_view_layout: Error inflating class android.webkit.WebView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createView(LayoutInflater.java:780)
        at androidx.asynclayoutinflater.view.AsyncLayoutInflater$BasicInflater.onCreateView(AsyncLayoutInflater.java:146)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:934)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:954)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at androidx.asynclayoutinflater.view.AsyncLayoutInflater$InflateThread.runInner(AsyncLayoutInflater.java:188)
        at androidx.asynclayoutinflater.view.AsyncLayoutInflater$InflateThread.run(AsyncLayoutInflater.java:202)
     Caused by: java.lang.RuntimeException: WebView cannot be initialized on a thread that has no Looper.
        at android.webkit.WebView.<init>(WebView.java:435)
        at android.webkit.WebView.<init>(WebView.java:363)
        at android.webkit.WebView.<init>(WebView.java:345)
        at android.webkit.WebView.<init>(WebView.java:332)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:858) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:780) 
        at androidx.asynclayoutinflater.view.AsyncLayoutInflater$BasicInflater.onCreateView(AsyncLayoutInflater.java:146) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:934) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:954) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538) 
        at androidx.asynclayoutinflater.view.AsyncLayoutInflater$InflateThread.runInner(AsyncLayoutInflater.java:188) 
        at androidx.asynclayoutinflater.view.AsyncLayoutInflater$InflateThread.run(AsyncLayoutInflater.java:202) 
```

**Comment by proninyaroslav** [comment]
@ln-12
Yes, only on UI thread.

**Comment by ln-12** [comment]
``````

**Comment by proninyaroslav** [comment]
@ln-12 
In my case, it still causes jank (like in my video), but delayed for some time. I'm using webview.

**Comment by proninyaroslav** [comment]
@bentrengrove 

What could be causing it? I'm using Compose Navigation. First, I load page A, then on a tap inside page A, page B is loaded (A goes to the backstack). Both pages use the same WebView instance. When I click the back button, then I go from page B to page A (from the backstack) and at that moment an exception occurs:
```
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
   at android.view.ViewGroup.addViewInner(ViewGroup.java:5248)
   at android.view.ViewGroup.addView(ViewGroup.java:5077)
   at android.view.ViewGroup.addView(ViewGroup.java:5017)
   at android.view.ViewGroup.addView(ViewGroup.java:4989)
   at androidx.compose.ui.viewinterop.AndroidViewHolder.setView$ui_release(AndroidViewHolder.android.kt:95)
   at androidx.compose.ui.viewinterop.ViewFactoryHolder.setFactory(AndroidView.android.kt:179)
   at androidx.compose.ui.viewinterop.AndroidView_androidKt$AndroidView$1.invoke(AndroidView.android.kt:116)
   at androidx.compose.ui.viewinterop.AndroidView_androidKt$AndroidView$1.invoke(AndroidView.android.kt:113)
   at androidx.compose.ui.viewinterop.AndroidView_androidKt$AndroidView$$inlined$ComposeNode$1.invoke(Composables.kt:254)
```

**Comment by ln-12** [comment]
@proninyaroslav I would guess that the problem in your case is that the view is attached to more than one layout (parent) at that moment. In my app, the webview is used on pages that will never be shown at the same time and therefore the view instance is only used in one layout. Did you try to use one view instance for each page instead?

**Comment by proninyaroslav** [comment]
@ln-12 
Yes, I store the WebView object in the root activity and pass it through the `CompositionLocal` down the tree. I think the problem is that I'm using Navigation which adds pages to the backstack
