### ISSUE TITLE
[Pager] crash at DelegatableNodeKt.requireOwner (NPE)

### ISSUE THREAD

**Issue by dokinkon** [google/accompanist#1439]
**Description**
HorizontalPager crash with NPE

```
java.lang.NullPointerException
    at androidx.compose.ui.node.DelegatableNodeKt.requireOwner(DelegatableNode.kt:308)
    at androidx.compose.ui.node.SemanticsModifierNodeKt.invalidateSemantics(SemanticsModifierNode.kt:44)
    at androidx.compose.ui.node.NodeKindKt.autoInvalidateNode(NodeKind.kt:171)
    at androidx.compose.ui.node.NodeChain.updateNodeAndReplaceIfNeeded(NodeChain.kt:513)
    at androidx.compose.ui.node.NodeChain.updateFrom$ui_release(NodeChain.kt:130)
    at androidx.compose.ui.node.LayoutNode.setModifier(LayoutNode.kt:735)
    at androidx.compose.ui.node.ComposeUiNode$Companion$SetModifier$1.invoke(ComposeUiNode.kt:42)
    at androidx.compose.ui.node.ComposeUiNode$Companion$SetModifier$1.invoke(ComposeUiNode.kt:42)
    at androidx.compose.runtime.ComposerImpl$apply$operation$1.invoke(Composer.kt:1621)
    at androidx.compose.runtime.ComposerImpl$apply$operation$1.invoke(Composer.kt:1619)
    at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:808)
    at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:839)
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:585)
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:503)
    at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
    at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
    at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
    at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1018)
    at android.view.Choreographer.doCallbacks(Choreographer.java:840)
    at android.view.Choreographer.doFrame(Choreographer.java:763)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1002)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:268)
    at android.app.ActivityThread.main(ActivityThread.java:8016)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```

**Steps to reproduce**
Create HorizontalPage, swipe it and change page a while, then app crash.

**Expected behavior** 
No crash.

**Additional context**
accompanistVersion = 0.28.0
composeVersion = "1.4.0-alpha02"

Thank you.

**Comment by andkulikov** [comment]
Is there a chance you can provide a sample code which reproduces the issue? Thanks

**Comment by xiebingfeng** [comment]
> Is there a chance you can provide a sample code which reproduces the issue? Thanks

create some LazyColumn in HorizontalPager ,then add clickable modifier in item.
swipe left or right slow,then crash

**Comment by andkulikov** [comment]
Sorry, but unfortunately that is still not enough. I tried to run such code
```
            val list = List(100) { it }
            LazyColumn {
                //crash:  must   1.itemsIndexed  2.clickable
                itemsIndexed(list) { index, item ->
                    Text(text = ("123" + " ").repeat(160), modifier = Modifier
                        .padding(vertical = 30.dp)
                        .width(400.dp)
                        .clickable { })
                }
            }
```
And it is not crashing to me

**Comment by andkulikov** [comment]
This issue is fixed now in compose:ui codebase

**Comment by BcanGRG** [comment]
> This issue is fixed now in compose:ui codebase

We have the same problems in version 1.5.0-alpha02.
What should we do ?
