### ISSUE TITLE
[Navigation Material] BottomSheet crash when closing (0.29.0-alpha)

### ISSUE THREAD

**Issue by miduch** [google/accompanist#1473]
**Description**

crash happens in 0.29.0-alpha when bottom sheet is being closed 

java.lang.NoSuchMethodError: No virtual method snapTo(Ljava/lang/Object;Lkotlin/coroutines/Continuation;)Ljava/lang/Object; in class Landroidx/compose/material/ModalBottomSheetState; or its super classes (declaration of 'androidx.compose.material.ModalBottomSheetState' appears in /data/app/~~Zr5_rXdHi-owlzeQxukd5w==/com.example.myapp.debug-uTDaE_no6JsJGsnvmnYZBg==/base.apk)
                 	at com.google.accompanist.navigation.material.SheetContentHostKt.internalHide(SheetContentHost.kt:182)
                 	at com.google.accompanist.navigation.material.SheetContentHostKt.access$internalHide(SheetContentHost.kt:1)
                 	at com.google.accompanist.navigation.material.SheetContentHostKt$SheetContentHost$2$2$1.invokeSuspend(SheetContentHost.kt:142)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                 	at android.os.Handler.handleCallback(Handler.java:942)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7872)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Steps to reproduce**

**Expected behavior** 
No crash 

**Additional context**

**Comment by jossiwolf** [comment]
`internalHide` doesn't exist in `v0.29.0-alpha` anymore. Check that you are using the right versions and clear your caches - if that doesn't help, please create a repro for us to check with.

**Comment by miduch** [comment]
was getting 0.28.0 as transitive dependency, works now

thanks!
