### ISSUE TITLE
I cannot use Compose preview 

### ISSUE THREAD

**Issue by BraveHL** [google/accompanist#1514]
## Describe the bug
I used the default compose use case of Android studio, created a new project, it can be previewed, then I changed the value of the parameter string in the @Preview, the preview map automatically refreshed, and then failed, I restored the parameters, and then the preview map automatically refreshed, still the preview failed, please fix this problem as soon as possible,

I saw the error log, but don't know how to fix it, no one seems to have come across it, the log is as follows，My JDK version is 11

java.lang.NoSuchMethodError: 'void com.example.myapplication111.ui.theme.ThemeKt.MyApplication111Theme$default(boolean, _layoutlib_._internal_.kotlin.jvm.functions.Function0, int, java.lang.Object)'   at com.example.myapplication111.MainActivityKt.DefaultPreview(MainActivity.kt:40)   at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)   at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)   at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)   at java.lang.reflect.Method.invoke(Method.java:566)   at androidx.compose.ui.tooling.ComposableInvoker.invokeComposableMethod(ComposableInvoker.kt:155)   at androidx.compose.ui.tooling.ComposableInvoker.invokeComposable(ComposableInvoker.kt:195)   at androidx.compose.ui.tooling.ComposeViewAdapter$init$3$1$composable$1.invoke(ComposeViewAdapter.kt:590)   at androidx.compose.ui.tooling.ComposeViewAdapter$init$3$1$composable$1.invoke(ComposeViewAdapter.kt:588)   at androidx.compose.ui.tooling.ComposeViewAdapter$init$3$1.invoke(ComposeViewAdapter.kt:625)   at androidx.compose.ui.tooling.ComposeViewAdapter$init$3$1.invoke(ComposeViewAdapter.kt:583)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)   at androidx.compose.ui.tooling.InspectableKt.Inspectable(Inspectable.kt:61)   at androidx.compose.ui.tooling.ComposeViewAdapter$WrapPreview$1.invoke(ComposeViewAdapter.kt:531)   at androidx.compose.ui.tooling.ComposeViewAdapter$WrapPreview$1.invoke(ComposeViewAdapter.kt:530)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)   at androidx.compose.ui.tooling.ComposeViewAdapter.WrapPreview(ComposeViewAdapter.kt:525)   at androidx.compose.ui.tooling.ComposeViewAdapter.access$WrapPreview(ComposeViewAdapter.kt:124)   at androidx.compose.ui.tooling.ComposeViewAdapter$init$3.invoke(ComposeViewAdapter.kt:583)   at androidx.compose.ui.tooling.ComposeViewAdapter$init$3.invoke(ComposeViewAdapter.kt:580)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)   at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:402)   at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:248)   at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:247)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)   at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:177)   at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:123)   at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:122)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)   at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:114)   at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:157)   at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:156)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)   at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:156)   at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:140)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)   at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:74)   at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3193)   at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3183)   at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:252)   at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations  at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3183)   at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3119)   at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:584)   at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:811)   at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)   at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)   at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)   at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1015)   at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)   at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:182)   at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)   at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)   at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)   at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)   at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1102)   at android.view.View.dispatchAttachedToWindow(View.java:21291)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)   at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:58) Copy stack to clipboard
![image](https://user-images.githubusercontent.com/22335503/218661262-1fa6ee7d-165a-4003-94b6-49aafe719385.png)

## Environment:
 - Android OS version: [e.g. Android 5.0]
 - Device: [e.g. Emulator, Google Pixel 4]
 - Accompanist version: [e.g. v0.X]

**Comment by alexvanyo** [comment]
Thank you for the issue, but I don't think this is related to accompanist?

Please use the [main issue tracker](https://issuetracker.google.com/issues?q=componentid:612128) for general Compose issues, as this issue tracker is just for accompanist libraries.
