### ISSUE TITLE
[Navigation Animation] java.util.NoSuchElementException: ArrayDeque is empty

### ISSUE THREAD

**Issue by muhfiz** [google/accompanist#1585]
**Description**
App Crashing when navigate - used version: 0.31.0-alpha, compose version: 1.4.0

**Steps to reproduce**

- Have this as navigator
```
class MyNavigator(navController: NavHostController) {

    val navigateToStart: () -> Unit = {
        navController.navigate(Destinations.START_ROUTE) {
            popUpTo(navController.graph.findStartDestination().id)
            launchSingleTop = true
        }
    }

    val navigateToAnother: () -> Unit = {
        navController.navigate(Destinations.ANOTHER_ROUTE) {
            popUpTo(navController.graph.findStartDestination().id)
            launchSingleTop = true
        }
    }
}
```
- Open App
- Navigate to settings by calling `navigateToAnother`
- From settings, navigate back to start by calling `navigateToStart` and the error produce here

**Expected behavior** 
Not crash

**Additional context**

And when i change the MyNavigator class like this

```
class MyNavigation(navController: NavHostController) {

    val navigateToStart: () -> Unit = {
        navController.navigate(Destinations.START_ROUTE) {
            popUpTo(Destinations.START_ROUTE)
            launchSingleTop = true
        }
    }

    val navigateToAnother: () -> Unit = {
        navController.navigate(Destinations.ANOTHER_ROUTE) {
            popUpTo(Destinations.START_ROUTE)
            launchSingleTop = true
        }
    }
}
```
it works just fine and even more just change the navigateToStart like this
```
    val navigateToStart: () -> Unit = {
        navController.navigate(Destinations.START_ROUTE) {
            popUpTo(Destinations.START_ROUTE)
            launchSingleTop = true
        }
    }
```
will work too

Error produced 
```
java.util.NoSuchElementException: ArrayDeque is empty.
at kotlin.collections.ArrayDeque.removeLast(ArrayDeque.kt:163)
at androidx.navigation.NavController.launchSingleTopInternal(NavController.kt:1848)
at androidx.navigation.NavController.navigate(NavController.kt:1809)
at androidx.navigation.NavController.navigate(NavController.kt:1772)
at androidx.navigation.NavController.navigate(NavController.kt:2173)
at androidx.navigation.NavController.navigate$default(NavController.kt:2168)
at androidx.navigation.NavController.navigate(NavController.kt:2153)
at mpl.bot.ui.MplBotNavigation$navigateToHome$1.invoke(MyNavigation.kt:12)
at mpl.bot.ui.MplBotNavigation$navigateToHome$1.invoke(MyNavigation.kt:11)
```

**Comment by muhfiz** [comment]
I think the problem in compose version, my bad :(
