### ISSUE TITLE
[Navigation Animation] No type arguments expected for interface AnimatedContentScope

### ISSUE THREAD

**Issue by gaohomway** [google/accompanist#1634]
**No type arguments expected for interface AnimatedContentScope**

<img width="1059" alt="截屏2023-05-21 18 53 22" src="https://github.com/google/accompanist/assets/5456137/a8d5b95d-3ac5-4f5c-b09e-37d0039468e0">

**Comment by jbw0033** [comment]
That API was changed to AnimatedContentTransitionScope in the [Compose Animation 1.5.0-alpha01 release](https://developer.android.com/jetpack/androidx/releases/compose-animation#1.5.0-alpha01).

**Comment by Tonnie-Dev** [comment]
Thanks Lot's guy, you are life savers

**Comment by gaohomway** [comment]
I still don't understand, can you give the specific code?

**Comment by gaohomway** [comment]
I replace `AnimatedContentScope` with `AnimatedContentTransitionScope` .

still have error.

```
java.lang.AssertionError: 1 trailing arguments were found in AnimatedContentScope<NavBackStackEntry> type
	at org.jetbrains.kotlin.descriptors.TypeParameterUtilsKt.buildPossiblyInnerType(typeParameterUtils.kt:87)
	at org.jetbrains.kotlin.descriptors.TypeParameterUtilsKt.buildPossiblyInnerType(typeParameterUtils.kt:76)
	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderTypeConstructorAndArguments(DescriptorRendererImpl.kt:277)
	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderTypeConstructorAndArguments$default(DescriptorRendererImpl.kt:273)
	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderDefaultType(DescriptorRendererImpl.kt:261)
	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderSimpleType(DescriptorRendererImpl.kt:178)
	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderNormalizedTypeAsIs(DescriptorRendererImpl.kt:153)
	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderNormalizedType(DescriptorRendererImpl.kt:131)
	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderFunctionType(DescriptorRendererImpl.kt:371)
	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderSimpleType(DescriptorRendererImpl.kt:176)
	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderNormalizedTypeAsIs(DescriptorRendererImpl.kt:153)
	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderNormalizedType(DescriptorRendererImpl.kt:131)
	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderType(DescriptorRendererImpl.kt:113)
	at org.jetbrains.kotlin.diagnostics.rendering.SmartTypeRenderer.render(smartRenderers.kt:28)
	at org.jetbrains.kotlin.diagnostics.rendering.SmartTypeRenderer.render(smartRenderers.kt:23)
	at org.jetbrains.kotlin.diagnostics.rendering.DiagnosticParameterRendererKt.renderParameter(DiagnosticParameterRenderer.kt:38)
	at org.jetbrains.kotlin.diagnostics.rendering.DiagnosticWithParameters2Renderer.renderParameters(diagnosticsWithParameterRenderers.kt:55)
	at org.jetbrains.kotlin.diagnostics.rendering.DiagnosticWithParameters2Renderer.renderParameters(diagnosticsWithParameterRenderers.kt:46)
	at org.jetbrains.kotlin.diagnostics.rendering.AbstractDiagnosticWithParametersRenderer.render(diagnosticsWithParameterRenderers.kt:27)
	at org.jetbrains.kotlin.diagnostics.rendering.DefaultErrorMessages.render(DefaultErrorMessages.java:53)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport$Companion.reportDiagnostic(AnalyzerWithCompilerReport.kt:150)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport$Companion.reportDiagnostics(AnalyzerWithCompilerReport.kt:173)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport$Companion.reportDiagnostics(AnalyzerWithCompilerReport.kt:183)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:124)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:248)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:88)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:167)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:101)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:485)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:131)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:424)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:360)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:242)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:625)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1746)
	at jdk.internal.reflect.GeneratedMethodAccessor115.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by vladmircan** [comment]
@gaohomway I know I am late for the answer, but for anyone else searching for the solution:

The "_1 trailing arguments were found in AnimatedContentScope<NavBackStackEntry> type_" error is caused by other dependencies that are not aligned with the compose version `1.5`.
To solve the problem, you need to update all dependencies that may depend/use compose internally: `accompanist`, etc.

Hope this helps somebody.

**Comment by mahdiTarighat** [comment]
> I replace `AnimatedContentScope` with `AnimatedContentTransitionScope` .
> 
> still have error.
> 
> ```
> java.lang.AssertionError: 1 trailing arguments were found in AnimatedContentScope<NavBackStackEntry> type
> 	at org.jetbrains.kotlin.descriptors.TypeParameterUtilsKt.buildPossiblyInnerType(typeParameterUtils.kt:87)
> 	at org.jetbrains.kotlin.descriptors.TypeParameterUtilsKt.buildPossiblyInnerType(typeParameterUtils.kt:76)
> 	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderTypeConstructorAndArguments(DescriptorRendererImpl.kt:277)
> 	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderTypeConstructorAndArguments$default(DescriptorRendererImpl.kt:273)
> 	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderDefaultType(DescriptorRendererImpl.kt:261)
> 	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderSimpleType(DescriptorRendererImpl.kt:178)
> 	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderNormalizedTypeAsIs(DescriptorRendererImpl.kt:153)
> 	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderNormalizedType(DescriptorRendererImpl.kt:131)
> 	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderFunctionType(DescriptorRendererImpl.kt:371)
> 	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderSimpleType(DescriptorRendererImpl.kt:176)
> 	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderNormalizedTypeAsIs(DescriptorRendererImpl.kt:153)
> 	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderNormalizedType(DescriptorRendererImpl.kt:131)
> 	at org.jetbrains.kotlin.renderer.DescriptorRendererImpl.renderType(DescriptorRendererImpl.kt:113)
> 	at org.jetbrains.kotlin.diagnostics.rendering.SmartTypeRenderer.render(smartRenderers.kt:28)
> 	at org.jetbrains.kotlin.diagnostics.rendering.SmartTypeRenderer.render(smartRenderers.kt:23)
> 	at org.jetbrains.kotlin.diagnostics.rendering.DiagnosticParameterRendererKt.renderParameter(DiagnosticParameterRenderer.kt:38)
> 	at org.jetbrains.kotlin.diagnostics.rendering.DiagnosticWithParameters2Renderer.renderParameters(diagnosticsWithParameterRenderers.kt:55)
> 	at org.jetbrains.kotlin.diagnostics.rendering.DiagnosticWithParameters2Renderer.renderParameters(diagnosticsWithParameterRenderers.kt:46)
> 	at org.jetbrains.kotlin.diagnostics.rendering.AbstractDiagnosticWithParametersRenderer.render(diagnosticsWithParameterRenderers.kt:27)
> 	at org.jetbrains.kotlin.diagnostics.rendering.DefaultErrorMessages.render(DefaultErrorMessages.java:53)
> 	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport$Companion.reportDiagnostic(AnalyzerWithCompilerReport.kt:150)
> 	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport$Companion.reportDiagnostics(AnalyzerWithCompilerReport.kt:173)
> 	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport$Companion.reportDiagnostics(AnalyzerWithCompilerReport.kt:183)
> 	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:124)
> 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:248)
> 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:88)
> 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
> 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:167)
> 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
> 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:101)
> 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
> 	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
> 	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:485)
> 	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:131)
> 	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:424)
> 	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:360)
> 	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:242)
> 	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:98)
> 	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:625)
> 	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:101)
> 	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1746)
> 	at jdk.internal.reflect.GeneratedMethodAccessor115.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
> 	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
> 	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
> 	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
> 	at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
> 	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
> 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
> 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
> 	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
> 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> ```

Upgrading to Accompanist should be fine.
