### ISSUE TITLE
[Permissions] After I started using accompanist-permissions:0.33.0-alpha, My app started crashing at lazy column

### ISSUE THREAD

**Issue by sureshmaidaragi1919** [google/accompanist#1701]
**Description**

I am trying to learn permission on compose, I imported the latest dep
`    implementation "com.google.accompanist:accompanist-permissions:0.33.0-alpha"
`
post adding a dependency, my app started crashing and if I remove dependency and related code app works fine

**Steps to reproduce**

**Expected behavior** 

**Additional context**

I am using pulltorefresh from dependency
` implementation 'androidx.compose.material:material-android:1.5.0'
`

Logs

```
2023-08-16 17:42:18.011 14703-14703 AndroidRuntime          com.example.composelazycolumn        E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.composelazycolumn, PID: 14703
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt;
                                                                                                    	at androidx.compose.material.pullrefresh.PullRefreshState.<init>(PullRefreshState.kt:125)
                                                                                                    	at
                                                                                                    androidx.compose.material.pullrefresh.PullRefreshStateKt.rememberPullRefreshState-UuyPYSY(PullRefreshState.kt:76)
                                                                                                    	at com.example.composelazycolumn.ui.PostContainerScreenKt.ShowList(PostContainerScreen.kt:90)
                                                                                                    	at com.example.composelazycolumn.ui.PostContainerScreenKt.PostContainerScreen(PostContainerScreen.kt:62)
                                                                                                    	at com.example.composelazycolumn.ui.PostContainerScreenKt$PostContainerScreen$1.invoke(Unknown Source:10)
                                                                                                    	at com.example.composelazycolumn.ui.PostContainerScreenKt$PostContainerScreen$1.invoke(Unknown Source:10)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2511)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2780)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3259)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3210)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:864)
                                                                                                    	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1125)
                                                                                                    	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:580)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:548)
                                                                                                    	at
                                                                                                    androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                                                                                                    	at
                                                                                                    androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at
                                                                                                    androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at
                                                                                                    androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:827)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@eae6ace, androidx.compose.ui.platform.MotionDurationScaleImpl@e226def, StandaloneCoroutine{Cancelling}@801d0fc, AndroidUiDispatcher@55af385]
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class
                                                                                                    "androidx.compose.runtime.PrimitiveSnapshotStateKt" on path: DexPathList[[dex file
                                                                                                    "/data/data/com.example.composelazycolumn/code_cache/.overlay/base.apk/classes6.dex", dex file
                                                                                                    "/data/data/com.example.composelazycolumn/code_cache/.overlay/base.apk/classes7.dex", zip file
                                                                                                    "/data/app/~~GWzKp5sgGKkdivwt8MMqlQ==/com.example.composelazycolumn-kvb-jprrbnYw2zp19ME_ww==/base.apk"],nativeLibraryDirectories=[/data/app/~~GWzKp5sgGKkdivwt8MMqlQ==/com.example.composelazycolumn-kvb-jprrbnYw2zp19ME_ww==/lib/arm64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	... 33 more
2023-08-16 17:42:18.026 14703-14703 Process                 com.example.composelazycolumn        I  Sending signal. PID: 14703 SIG: 9

```

**Comment by bentrengrove** [comment]
This looks like you have mismatched your Compose version with your Accompanist version?
0.33-alpha links to Compose 1.6. If you are still on Compose 1.5, make sure to use a v0.31 version

**Comment by sureshmaidaragi1919** [comment]
oh I see, now I updated compose version to [1.6.0-alpha03] It worked fine thanks for the Help @bentrengrove (https://developer.android.com/jetpack/androidx/releases/compose-material#1.6.0-alpha03)
