### ISSUE TITLE
Landroidx/compose/material/ModalBottomSheetKt; or its super classes 

### ISSUE THREAD

**Issue by Palmer1985** [google/accompanist#1713]
## Describe the bug
import stripe
android target sdk 34

Process: com.leorano.android.dev, PID: 2170
    java.lang.NoSuchMethodError: No static method ModalBottomSheetLayout-BzaUkTc(Lkotlin/jvm/functions/Function3;Landroidx/compose/ui/Modifier;Landroidx/compose/material/ModalBottomSheetState;Landroidx/compose/ui/graphics/Shape;FJJJLkotlin/jvm/functions/Function2;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/material/ModalBottomSheetKt; or its super classes (declaration of 'androidx.compose.material.ModalBottomSheetKt' appears in /data/app/~~YP1f73zDIWlMhAdtKm1QmQ==/com.leorano.android.dev-4n5gElO44-t3aRG_oQWz8A==/base.apk)
        at com.stripe.android.common.ui.BottomSheetKt.BottomSheet(BottomSheet.kt:166)
        at com.stripe.android.paymentsheet.PaymentSheetActivity$onCreate$2$1.invoke(PaymentSheetActivity.kt:77)
        at com.stripe.android.paymentsheet.PaymentSheetActivity$onCreate$2$1.invoke(PaymentSheetActivity.kt:62)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
        at androidx.compose.material.MaterialTheme_androidKt.PlatformMaterialTheme(MaterialTheme.android.kt:23)
        at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:82)
        at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:81)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:396)
        at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:81)
        at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:80)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:72)
        at com.stripe.android.uicore.StripeThemeKt$StripeTheme$1.invoke(StripeTheme.kt:331)
        at com.stripe.android.uicore.StripeThemeKt$StripeTheme$1.invoke(StripeTheme.kt:330)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at com.stripe.android.uicore.StripeThemeKt.StripeTheme(StripeTheme.kt:325)
        at com.stripe.android.paymentsheet.PaymentSheetActivity$onCreate$2.invoke(PaymentSheetActivity.kt:62)
        at com.stripe.android.paymentsheet.PaymentSheetActivity$onCreate$2.invoke(PaymentSheetActivity.kt:61)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
        at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:428)
        at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
        at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:195)
2023-09-23 09:18:55.620 2170-2170/com.leorano.android.dev E/AndroidRuntime:     at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:119)
        at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:118)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:110)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:158)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:157)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:157)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:142)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
        at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3340)
        at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3273)
        at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:588)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1013)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:520)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:142)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
        at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1191)
        at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:133)
        at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:183)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
        at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1266)
        at android.view.View.dispatchAttachedToWindow(View.java:21407)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3509)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2969)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2476)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9331)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1390)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1398)
2023-09-23 09:18:55.620 2170-2170/com.leorano.android.dev E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:1040)
        at android.view.Choreographer.doFrame(Choreographer.java:954)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1370)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2023-09-23 09:18:56.474 3705-3777/com.leorano.android.dev E/libEGL: pre_cache appList: ,,
2023-09-23 09:18:56.510 3705-3705/com.leorano.android.dev E/Intercom: Api call failed: A network request was made with no user registered on this device.Please call registerUnidentifiedUser() or registerIdentifiedUser(Registration).

**Comment by Palmer1985** [comment]
@bentrengrove

**Comment by Mik77o** [comment]
We encounter the same issue with SDK 34 and `flutter_stripe` 9.5.0! 🐛
