### ISSUE TITLE
[Permissions] Gradle update crashing permission request and the app

### ISSUE THREAD

**Issue by qsdigor** [google/accompanist#1746]
**Description**
Updating gradle version from 8.2.1 to 8.2.2 will crash the permission request.

Here is the crash log.
```
 java.lang.IllegalStateException: ActivityResultLauncher cannot be null
at com.google.accompanist.permissions.MutablePermissionState.launchPermissionRequest(MutablePermissionState.kt:94)
```

**Steps to reproduce**
Start any permission request. One sample for posting notification requests.
```
val notificationPermissionState = rememberPermissionState(Manifest.permission.POST_NOTIFICATIONS)
notificationPermissionState.launchPermissionRequest()
```

**Expected behavior** 
Launch the request and show the system dialog for the requested permission.

**Comment by bentrengrove** [comment]
I haven't been able to reproduce this in the Accompanist sample app unfortunately which runs 8.2.2 so I think something else must be going on. Do you have any more info or a minimal sample project that reproduces it?

**Comment by Mwhite69** [comment]
If the original site

**Comment by qsdigor** [comment]
It might be that I am launching permission requests in compose view with Timer but I did try without a timer and the same behaviour occurred.

```
Timer().schedule(timerTask {
    notificationPermissionState.launchPermissionRequest()
}, 1000)
```

**Comment by bentrengrove** [comment]
Have you had a look at the Accompanist sample app and seen if there is any difference to your implementation? Without more information I don't think I can provide a fix for this

**Comment by PalankiBharat** [comment]
I also am facing the same issue. I have the same implementation as the Sample
`  val multiplePermission = rememberMultiplePermissionsState(
                permissions = listOf(
                    Manifest.permission.READ_EXTERNAL_STORAGE,
                    Manifest.permission.WRITE_EXTERNAL_STORAGE,
                    Manifest.permission.RECORD_AUDIO
                ),
                onPermissionsResult = {

                }
            )
            multiplePermission.launchMultiplePermissionRequest()`

**Comment by PalankiBharat** [comment]
> **Description** Updating gradle version from 8.2.1 to 8.2.2 will crash the permission request.
> 
> Here is the crash log.
> 
> ```
>  java.lang.IllegalStateException: ActivityResultLauncher cannot be null
> at com.google.accompanist.permissions.MutablePermissionState.launchPermissionRequest(MutablePermissionState.kt:94)
> ```
> 
> **Steps to reproduce** Start any permission request. One sample for posting notification requests.
> 
> ```
> val notificationPermissionState = rememberPermissionState(Manifest.permission.POST_NOTIFICATIONS)
> notificationPermissionState.launchPermissionRequest()
> ```
> 
> **Expected behavior** Launch the request and show the system dialog for the requested permission.

Try to ask permission in LauncheEffect block

**Comment by Mwhite69** [comment]
Granted permissions ben

**Comment by qsdigor** [comment]
Launching permission request with LaunchedEffect did resolve the issue.

**Comment by PalankiBharat** [comment]
> Launching permission request with LaunchedEffect did resolve the issue.

Then maybe you could close the issue
