### ISSUE TITLE
BottomSheetNavigator#NullPointerException

### ISSUE THREAD

**Issue by tmxdyf** [google/accompanist#1767]
### Version
`com.google.accompanist:accompanist-navigation-material:0.35.0-alpha`

### Android SDK
android 8.1.0

### Crash Log
`Fatal Exception: java.lang.NullPointerException:
       at com.google.accompanist.navigation.material.BottomSheetNavigator$sheetContent$1$2.invoke(BottomSheetNavigator.java:327)
       at com.google.accompanist.navigation.material.BottomSheetNavigator$sheetContent$1$2.invoke(BottomSheetNavigator.java:140)
       at androidx.activity.compose.BackHandlerKt$BackHandler$backCallback$1$1.handleOnBackPressed(BackHandler.kt:9)
       at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.kt:42)
       at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:5)
       at android.app.Activity.onKeyUp(Activity.java:3114)
       at android.view.KeyEvent.dispatch(KeyEvent.java:3416)
       at androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:107)
       at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:22)
       at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:19)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:486)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5791)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5654)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5151)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5204)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5170)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5307)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5178)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5364)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5151)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5204)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5170)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5178)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5151)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5204)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5170)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5340)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5509)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3170)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2671)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2662)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3147)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:325)
       at android.os.Looper.loop(Looper.java:142)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)`

**Comment by ianhanniballake** [comment]
Accompanist Navigation Material has been deprecated and is not receiving any further updates. You'll want to switch to the `androidx.compose.material:material-navigation` artifact introduced in [AndroidX Compose Material 1.7.0-alpha04](https://developer.android.com/jetpack/androidx/releases/compose-material#1.7.0-alpha04) and [file an issue on their issue tracker](https://issuetracker.google.com/issues/new?component=742043) if you're still seeing the same crash.
