### ISSUE TITLE
[ImageLoad] Provide more detailed error information for image load

### ISSUE THREAD

**Issue by RinOrz** [google/accompanist#271]
Sometimes, some Image loading libraries will report some stack errors that are not easy to understand, should you report the calling point of the error?

such as **CoilImage**, the important calling code line is missing:

> E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.androiddevchallenge, PID: 6832
    java.lang.IllegalArgumentException: width and height must be > 0.
        at coil.size.PixelSize.<init>(Size.kt:30)
        at coil.request.ImageRequest$Builder.size(ImageRequest.kt:505)
        at dev.chrisbanes.accompanist.coil.CoilImage__CoilKt$CoilImage$3$1.invoke-O0kMr_c(Coil.kt:164)
        at dev.chrisbanes.accompanist.coil.CoilImage__CoilKt$CoilImage$3$1.invoke(Coil.kt:156)
        at dev.chrisbanes.accompanist.imageloading.ImageLoad__ImageLoadKt$ImageLoad$loadState$2.invokeSuspend(ImageLoad.kt:80)
        at dev.chrisbanes.accompanist.imageloading.ImageLoad__ImageLoadKt$ImageLoad$loadState$2.invoke(Unknown Source:8)
        at dev.chrisbanes.accompanist.imageloading.ImageLoad__ImageLoadKt$ImageLoad$loadState$2.invoke(Unknown Source:4)
        at androidx.compose.runtime.SnapshotStateKt$produceState$3.invokeSuspend(SnapshotState.kt:543)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:84)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:43)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:60)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by chrisbanes** [comment]
I'm not sure what you mean here to be honest. The error is pretty clear: `width and height must be > 0`. The stack trace is a bit garbled due to it being run in a Kotlin Coroutine, but there's not much we can do about that.

**Comment by RinOrz** [comment]
> I'm not sure what you mean here to be honest. The error is pretty clear: `width and height must be > 0`. The stack trace is a bit garbled due to it being run in a Kotlin Coroutine, but there's not much we can do about that.

Yes, but I don’t know where the error is, because I call **CoilImage** in many **Composable**

**Comment by chrisbanes** [comment]
I'm not sure there's much else we can do here, this is just how Coroutines work.

**Comment by RinOrz** [comment]
@chrisbanes I have discovered the reason for this error. This error will appear randomly when loading res images using CoilImage. Note that it does not necessarily appear. Usually it crashes and reports this error after I run the program. Is this a coil problem? ? I request to reopen the issue

**Comment by okycelt** [comment]
@RinOrz, I got this error today as well and turned out there was no space left for `CoilImage` in `Column` after other composables rendered. It was not related to loading resource images. Try to use `requiredSizeIn` instead of `sizeIn` or check your layout.
