### ISSUE TITLE
SocketTimeoutException even though the url is reachable

### ISSUE THREAD

**Issue by abhishekdewan101** [google/accompanist#283]
## Describe the bug
When trying to load an image url I am seeing SocketTimeout exception even though the image is clearly available when loading the same url through a browser. 

For e.g
When I host the following Coil Image inside of a NavHost destination.
```
CoilImage(
        data = "https://cdn1-www.superherohype.com/assets/uploads/2013/11/batmane3-1.jpg",
        contentDescription = null,
        modifier = Modifier
            .size(150.dp, 200.dp)
            .border(
                5.dp,
                color = MaterialTheme.colors.onBackground,
                shape = RoundedCornerShape(10.dp)
            )
    )

```

I see the following log error

```
2021-03-23 22:40:27.955 15268-15306/com.abhishek101.gametracker W/System.err: java.net.SocketTimeoutException: timeout
2021-03-23 22:40:27.956 15268-15306/com.abhishek101.gametracker W/System.err:     at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:672)
2021-03-23 22:40:27.956 15268-15306/com.abhishek101.gametracker W/System.err:     at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:680)
2021-03-23 22:40:27.956 15268-15306/com.abhishek101.gametracker W/System.err:     at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:398)
2021-03-23 22:40:27.956 15268-15306/com.abhishek101.gametracker W/System.err:     at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:205)
2021-03-23 22:40:27.956 15268-15306/com.abhishek101.gametracker W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
2021-03-23 22:40:27.956 15268-15306/com.abhishek101.gametracker W/System.err:     at okhttp3.internal.cache.CacheInterceptor$1.read(CacheInterceptor.java:174)
2021-03-23 22:40:27.956 15268-15306/com.abhishek101.gametracker W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
2021-03-23 22:40:27.956 15268-15306/com.abhishek101.gametracker W/System.err:     at okio.ForwardingSource.read(ForwardingSource.kt:29)
2021-03-23 22:40:27.956 15268-15306/com.abhishek101.gametracker W/System.err:     at coil.decode.InterruptibleSource.read(InterruptibleSource.kt:78)
2021-03-23 22:40:27.956 15268-15306/com.abhishek101.gametracker W/System.err:     at okio.ForwardingSource.read(ForwardingSource.kt:29)
2021-03-23 22:40:27.956 15268-15306/com.abhishek101.gametracker W/System.err:     at coil.decode.BitmapFactoryDecoder$ExceptionCatchingSource.read(BitmapFactoryDecoder.kt:279)
2021-03-23 22:40:27.956 15268-15306/com.abhishek101.gametracker W/System.err:     at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
2021-03-23 22:40:27.956 15268-15306/com.abhishek101.gametracker W/System.err:     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
2021-03-23 22:40:27.956 15268-15306/com.abhishek101.gametracker W/System.err:     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:790)
2021-03-23 22:40:27.956 15268-15306/com.abhishek101.gametracker W/System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:765)
2021-03-23 22:40:27.956 15268-15306/com.abhishek101.gametracker W/System.err:     at coil.decode.BitmapFactoryDecoder.decodeInterruptible(BitmapFactoryDecoder.kt:170)
2021-03-23 22:40:27.956 15268-15306/com.abhishek101.gametracker W/System.err:     at coil.decode.BitmapFactoryDecoder.access$decodeInterruptible(BitmapFactoryDecoder.kt:28)
2021-03-23 22:40:27.957 15268-15306/com.abhishek101.gametracker W/System.err:     at coil.decode.BitmapFactoryDecoder.decode(BitmapFactoryDecoder.kt:41)
2021-03-23 22:40:27.957 15268-15306/com.abhishek101.gametracker W/System.err:     at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:428)
2021-03-23 22:40:27.957 15268-15306/com.abhishek101.gametracker W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2021-03-23 22:40:27.957 15268-15306/com.abhishek101.gametracker W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2021-03-23 22:40:27.957 15268-15306/com.abhishek101.gametracker W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2021-03-23 22:40:27.957 15268-15306/com.abhishek101.gametracker W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2021-03-23 22:40:27.957 15268-15306/com.abhishek101.gametracker W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2021-03-23 22:40:27.957 15268-15306/com.abhishek101.gametracker W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2021-03-23 22:43:34.057 15393-15431/com.abhishek101.gametracker D/skia: ---- read threw an exception
2021-03-23 22:43:34.058 15393-15431/com.abhishek101.gametracker D/skia: libjpeg error 105 <  Ss=0, Se=0, Ah=0, Al=0> from startDecompress
2021-03-23 22:43:34.058 15393-15431/com.abhishek101.gametracker D/skia: --- codec->getAndroidPixels() failed
```

## To Reproduce

The code that fails is present here https://github.com/abhishekdewan101/GameTracker/blob/9b61df7a84bf0b4e1e5e6c3629529cd95a82e257/app/src/main/java/com/abhishek101/gametracker/ui/features/home/HomeScreen.kt#L150

or you can place the above composable inside of LazyVerticalGrid and it should be reproducible. Also for reference count of the VerticalGrid is 8.

## Expected behavior
Image should load if the url is accessible via browser.

## Environment:
 - Android OS version:  API 29
 - Device: Emulator
 - Accompanist version: 0.6.2

**Comment by chrisbanes** [comment]
`SocketException` is obviously a network layer exception, which Accompanist has nothing to do with. I suggest you raise an issue on the main Coil library repository: https://github.com/coil-kt/coil

**Comment by chrisbanes** [comment]
FYI: the exception is due to a HTTP timeout, so you may want to try increasing your request timeout.

I’d be surprised if this is a bug in Coil.
