### ISSUE TITLE
GlideImage does not seem to display images

### ISSUE THREAD

**Issue by Nthily** [google/accompanist#294]
![image](https://user-images.githubusercontent.com/31311826/113069325-5d4ce180-91c0-11eb-8ad7-9b8a00adea44.png)

build.gradle

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

android {

    lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }

    compileSdkVersion 29
    buildToolsVersion '29.0.3'

    defaultConfig {
        applicationId "com.example.test"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }
    buildFeatures {
        compose true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
        useIR = true
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion compose_version
        kotlinCompilerVersion '1.4.30'
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.3.0-beta01'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha02'
    implementation "androidx.compose.ui:ui:$compose_version"
    implementation "androidx.compose.material:material:$compose_version"
    implementation "androidx.compose.ui:ui-tooling:$compose_version"
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.3.0'
    implementation 'androidx.activity:activity-compose:1.3.0-alpha03'


    implementation "androidx.compose.ui:ui-tooling:1.0.0-beta01"
    implementation 'androidx.core:core-ktx:1.5.0-beta02'
    implementation 'androidx.activity:activity-ktx:1.2.0'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.3.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha02'
    implementation "androidx.compose.foundation:foundation:$compose_version"
    implementation "androidx.compose.foundation:foundation-layout:$compose_version"
    implementation "androidx.compose.material:material:$compose_version"
    implementation "androidx.compose.ui:ui:$compose_version"
    implementation "androidx.compose.ui:ui-tooling:$compose_version"
    implementation "androidx.compose.ui:ui-util:$compose_version"
    implementation 'dev.chrisbanes.accompanist:accompanist-insets:0.6.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.room:room-runtime:2.2.6'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

    implementation "androidx.compose.material:material-icons-extended:$compose_version"

    def room_version = "2.2.6"

    implementation "androidx.room:room-runtime:$room_version"
    kapt "androidx.room:room-compiler:$room_version"

    // optional - Kotlin Extensions and Coroutines support for Room
    implementation "androidx.room:room-ktx:$room_version"

    // optional - Test helpers
    testImplementation "androidx.room:room-testing:$room_version"

    implementation "androidx.compose.runtime:runtime:1.0.0-beta02"
    implementation "androidx.compose.runtime:runtime-livedata:1.0.0-beta02"
    implementation "androidx.compose.runtime:runtime-rxjava2:1.0.0-beta02"

    implementation 'com.afollestad.material-dialogs:datetime:3.3.0'

    implementation "androidx.activity:activity-ktx:1.2.2"

    def fragment_version = "1.3.2"

    // Kotlin
    implementation "androidx.fragment:fragment-ktx:$fragment_version"
    // Testing Fragments in Isolation
    debugImplementation "androidx.fragment:fragment-testing:$fragment_version"


    implementation 'com.google.accompanist:accompanist-glide:0.7.0'

}
```

I dont know why

**Comment by chrisbanes** [comment]
Not enough information here. I’d check logcat to see what’s happening.

If I had to take a guess, it would be that you’re missing the Internet permission in the nee project.

**Comment by Nthily** [comment]
> Not enough information here. I’d check logcat to see what’s happening.
> 
> If I had to take a guess, it would be that you’re missing the Internet permission in the new project.

Thank you, it is true that you did not add networking permission

**Comment by Nthily** [comment]
> Not enough information here. I’d check logcat to see what’s happening.
> 
> If I had to take a guess, it would be that you’re missing the Internet permission in the new project.

But in my project, I selected an image from the album and it has some errors

Like this

**Comment by Nthily** [comment]
```
D/ContentValues: path + /storage/emulated/0/Android/data/com.example.fragmentsofmemory/files/picture.jpg
W/Glide: Load failed for /storage/emulated/0/Android/data/com.example.fragmentsofmemory/files/picture.jpg with size [193x193]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.lang.NullPointerException(Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{StringUri->Object->Drawable}, LOCAL
    There was 1 cause:
    java.lang.NullPointerException(Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{StringUri->Drawable->Drawable}
    There was 1 cause:
    java.lang.NullPointerException(Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{StringUri->Bitmap->Drawable}
I/Glide: Root cause (1 of 1)
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.bumptech.glide.load.resource.drawable.ResourceDrawableDecoder.handles(ResourceDrawableDecoder.java:54)
        at com.bumptech.glide.load.resource.drawable.ResourceDrawableDecoder.handles(ResourceDrawableDecoder.java:25)
        at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:90)
        at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
        at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
        at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
        at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
        at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:524)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:488)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:474)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:426)
        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:390)
        at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:148)
        at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:76)
        at com.bumptech.glide.load.model.UnitModelLoader$UnitFetcher.loadData(UnitModelLoader.java:55)
        at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
I/agmentsofmemor: ProcessProfilingInfo new_methods=9341 is saved saved_to_disk=1 resolve_classes_delay=8000
I/Toast: Show toast from OpPackageName:com.example.fragmentsofmemory, PackageName:com.example.fragmentsofmemory

```

**Comment by Nthily** [comment]
```
@Composable
fun Display() {
    val context = LocalContext.current
    val viewModel: UiModel = viewModel()
    if (viewModel.imageUriState.value != null) {

        val file = File(context.getExternalFilesDir(null), "picture.jpg")
        try {

            val getIS = context.contentResolver.openInputStream(viewModel.imageUriState.value!!)
            val os = FileOutputStream(file)
            val data = getIS?.available()?.let { byteArrayOf(it.toByte()) }
            getIS?.read(data)
            os.write(data)
            getIS?.close()
            os.close()
            Toast.makeText(context, "Upload successful", Toast.LENGTH_LONG).show()
            viewModel.testt
        } catch (e:IOException) {
            Toast.makeText(context, "Upload successful failed", Toast.LENGTH_LONG).show()
            Log.w("ExternalStorage", "Error writing $file", e);
        }
        Log.d(TAG, "path + ${Uri.parse(file.absolutePath)}")
        GlideImage(data = Uri.parse(file.absolutePath), contentDescription = null)
      //  GlideImage(data = "https://picsum.photos/300/300", fadeIn = true)
        //  Log.d(TAG, "${Uri.parse(file.absolutePath)}")
    }
}
```

**Comment by Nthily** [comment]
Normally, I have assigned an absolute path to an image, but it seems to show a null error

**Comment by Nthily** [comment]
Sorry, I solved the error, because I wrote the wrong code to read the image

**Comment by Nthily** [comment]
The correct way to write it should be like this, thank you for your help !
```
            val getIS = context.contentResolver.openInputStream(viewModel.imageUriState.value!!)
            val os = FileOutputStream(file)
            val data = ByteArray(getIS!!.available())
            getIS.read(data)
            os.write(data)
            getIS.close()
            os.close()
            Toast.makeText(context, "Upload successful", Toast.LENGTH_LONG).show()
```
