### ISSUE TITLE
[CoilImage] can't display the image when limit size 3/4 in modifier and the image is 10/3

### ISSUE THREAD

**Issue by jinguoliang** [google/accompanist#306]
## Describe the bug
the stack track is：
2021-04-02 17:33:53.954 4687-4687/com.jinux.exercise_helper E/ComposableSingletons$MainActivityKt$lambda-3: java.lang.IllegalStateException: BitmapFactory returned a null Bitmap. Often this means BitmapFactory could not decode the image data read from the input source (e.g. network or disk) as it's not encoded as a valid image format.
        at coil.decode.BitmapFactoryDecoder.decodeInterruptible(BitmapFactoryDecoder.kt:183)
        at coil.decode.BitmapFactoryDecoder.access$decodeInterruptible(BitmapFactoryDecoder.kt:28)
        at coil.decode.BitmapFactoryDecoder.decode(BitmapFactoryDecoder.kt:41)
        at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:428)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

## To Reproduce

The test code：

@Composable
fun TestCoilImage() {
    val activity = LocalContext.current as Activity
    Column(modifier = Modifier.fillMaxSize()) {
        CoilImage(data = Uri.parse("content://com.jinux.app.fileprovider/resources/a93a9d7a-f0af-489a-8930-33d71ad441b1")) {
            when(it) {
                is ImageLoadState.Success -> {
                    Image(painter = it.painter, contentDescription = null)
                }
                is ImageLoadState.Error -> {
                    Timber.e(Log.getStackTraceString(it.throwable))
                }
                else -> {}
            }
        }
        Button(onClick = {
            if (activity.requestedOrientation == ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE) {
                activity.requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
            } else {
                activity.requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE
            }
        }) {
            Text("Change Orientation")
        }
    }
}

the image：

![testpng](https://user-images.githubusercontent.com/1611550/113404191-58637a00-93da-11eb-818d-93c2064141ba.png)

**Comment by chrisbanes** [comment]
Looks like this is because `Coil`'s `Precision.AUTOMATIC` only works when using the built-in automatic view size resolver which we can't use.

**Comment by chrisbanes** [comment]
You can workaround this yourself:

``` kotlin
CoilImage(
    data = ...,
    requestBuilder = { precision(Precision.INEXACT) },
)
```
