### ISSUE TITLE
[Coil] Fatal Exception: java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by pedrovgs** [google/accompanist#371]
## Describe the bug

Samsung Galaxy S9 running Android 10 crashes when loading an image from the local storage. ``accompanist-coil`` throws this exception:

```java
Fatal Exception: java.lang.AbstractMethodError: abstract method "boolean com.google.accompanist.imageloading.ShouldRefetchOnSizeChange.invoke-O0kMr_c(com.google.accompanist.imageloading.ImageLoadState, long)"
       at com.google.accompanist.imageloading.LoadPainter.execute-JVtK1S4(LoadPainter.kt:273)
       at com.google.accompanist.imageloading.LoadPainter$onRemembered$1$4.invokeSuspend(LoadPainter.kt:255)
       at com.google.accompanist.imageloading.LoadPainter$onRemembered$1$4.invoke(:8)
       at com.google.accompanist.imageloading.LoadPainter$onRemembered$1$4.invoke(:4)
       at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:214)
       at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(:12)
       at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$invokeSuspend$$inlined$collect$1$lambda$1.invokeSuspend(Merge.kt:34)
       at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$invokeSuspend$$inlined$collect$1$lambda$1.invoke(:10)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
       at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
       at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
       at kotlinx.coroutines.BuildersKt.launch(:1)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:49)
       at kotlinx.coroutines.BuildersKt.launch$default(:1)
       at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$invokeSuspend$$inlined$collect$1.emit(Collect.kt:138)
       at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$unsafeFlow$1$lambda$1.invokeSuspend(Zip.kt:33)
       at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$unsafeFlow$1$lambda$1.invoke(:14)
       at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:79)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
       at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

## To Reproduce

I can't reproduce this error manually. The only thing I know is the app crashes on Samsung S9 devices running Android 10.

## Expected behavior

The library should not crash.

## Environment:
 - Android OS version: Android 10.
 - Device: Samsung Galaxy S9.
 - Accompanist version: 0.8.0

**Comment by chrisbanes** [comment]
Thanks for the report. What does the calling code look like? Using `CoilImage()`?

**Comment by pedrovgs** [comment]
This is the code:

```kotlin
CoilImage(
            data = data,
            contentDescription = imageContentDescription,
            fadeIn = true,
            requestBuilder = requestBuilder,
            loading = { loadingContent() },
            error = { errorInfo ->
                Timber.d("Error loading image from $data = $errorInfo")
                errorContent()
            },
            modifier = modifier,
            contentScale = contentScale
        )
```

I see now ``CoilImage`` is deprecated. Do you think migrating to ``Image`` will fix the issue?

**Comment by chrisbanes** [comment]
Ah I think I see the likely issue: we're using a `lambda` and passing that through to a `fun interface`, which might be confusing the compiler.

> Do you think migrating to `Image` will fix the issue?

Yes, since you'll be using the `fun interface ShouldRefetchOnSizeChange` directly.

**Comment by pedrovgs** [comment]
Great! I guess as this is only an issue related to a deprecated API and there is a workaround as soon as you consider it ready, you can close it. Thank you so much for your time and quick response 😃

**Comment by chrisbanes** [comment]
Hmmm, looking at the generated bytecode I can't see an issue (which would explain why it works for me locally + tests). Maybe this is something to do with R8 release builds?

**Comment by aconda-mercari** [comment]
Consistently crashes on emulator for me when rotating the device, after I added all the possible values on `android:configChange` for the pure-compose project.
