### ISSUE TITLE
SocketTimeoutException -> ImageStateLoad.Error?

### ISSUE THREAD

**Issue by hlnstepanova** [google/accompanist#381]
When I try loading an image that is too big, the app crashes with a Socket TimeoutException. May be it is possible to catch it and return ImageStateLoad.Error?

D/skia: ---- read threw an exception
    libjpeg error 105 <  Ss=0, Se=63, Ah=0, Al=0> from Incomplete image data
W/System.err: java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:672)
W/System.err:     at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:680)
        at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:398)
        at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:205)
W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
        at okio.ForwardingSource.read(ForwardingSource.kt:29)
        at coil.decode.InterruptibleSource.read(InterruptibleSource.kt:78)
W/System.err:     at okio.ForwardingSource.read(ForwardingSource.kt:29)
        at coil.decode.BitmapFactoryDecoder$ExceptionCatchingSource.read(BitmapFactoryDecoder.kt:281)
        at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
        at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
W/System.err:     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:838)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:813)
W/System.err:     at coil.decode.BitmapFactoryDecoder.decodeInterruptible(BitmapFactoryDecoder.kt:172)
        at coil.decode.BitmapFactoryDecoder.access$decodeInterruptible(BitmapFactoryDecoder.kt:27)
        at coil.decode.BitmapFactoryDecoder.decode(BitmapFactoryDecoder.kt:39)
W/System.err:     at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:426)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by chrisbanes** [comment]
Hmmm, I have no idea how this is happening. Both [Coil](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/RealImageLoader.kt#L193) and [Accompanist](https://github.com/google/accompanist/blob/main/imageloading-core/src/main/java/com/google/accompanist/imageloading/LoadPainter.kt#L319) handle exceptions and wrap them up, so I'm struggling to see a way in which this happens.

Do you have any sample code which triggers this?

**Comment by hlnstepanova** [comment]
Can you try this? https://github.com/hlnstepanova/ComposeCoilTest
As far as I tested, it crashed silently every time when I run it on Android 9, but it seems to work well on Android 11

**Comment by chrisbanes** [comment]
I can't recreate this on any API level. I don't see any crashes, and each of the results correctly gets wrapped in an `Error` instance.

Honestly I'm not surprised that this isn't working very well though, the sample is loading a 23680x2144 20MB image repeatedly in a list, to be displayed in a `48.dp` box.
