### ISSUE TITLE
[CRASH][PAGER] Vertical Image gallery

### ISSUE THREAD

**Issue by Fed93** [google/accompanist#398]
## Describe the bug
Application crash when return from background due to bitmap recycle **(only in ViewPager, not happening in normal LazyColumn/Row)** using Glide accompanist lib.

## To Reproduce

1. Create a VerticalPager with images as content
2. Put app in background
3. Reopen

## Environment:
 - Android OS version: Android 10/11
 - Device: Emulator, OnePlus 6T
 - Accompanist version: v0.9.1

## Additional context (StackTrace)
    java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@b67ba92
        at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:66)
        at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:277)
        at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
        at androidx.compose.ui.graphics.AndroidCanvas.drawImageRect-HPBpro0(AndroidCanvas.android.kt:275)
        at androidx.compose.ui.graphics.drawscope.CanvasDrawScope.drawImage-riqrfck(CanvasDrawScope.kt:227)
        at androidx.compose.ui.node.LayoutNodeDrawScope.drawImage-riqrfck(Unknown Source:44)
        at androidx.compose.ui.graphics.drawscope.DrawScope$DefaultImpls.drawImage-riqrfck$default(DrawScope.kt:459)
        at androidx.compose.ui.graphics.painter.BitmapPainter.onDraw(BitmapPainter.kt:55)
        at androidx.compose.ui.graphics.painter.Painter.draw-x_KDEd0(Painter.kt:212)
        at com.google.accompanist.imageloading.LoadPainter.onDraw(LoadPainter.kt:229)
        at androidx.compose.ui.graphics.painter.Painter.draw-x_KDEd0(Painter.kt:212)
        at androidx.compose.ui.draw.PainterModifier.draw(PainterModifier.kt:289)
        at androidx.compose.ui.node.ModifiedDrawNode.performDraw(ModifiedDrawNode.kt:102)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:209)
        at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:82)
        at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:220)
        at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:219)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:121)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:75)
        at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:219)
        at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:51)
        at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:156)
        at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:221)
        at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:202)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:204)
        at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:82)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:209)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:70)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:209)
        at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:794)
        at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:119)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:209)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:70)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:209)
        at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:42)
        at androidx.compose.material.ripple.AndroidRippleIndicationInstance.drawIndication(Ripple.android.kt:202)
        at androidx.compose.foundation.IndicationModifier.draw(Indication.kt:175)
        at androidx.compose.ui.node.ModifiedDrawNode.performDraw(ModifiedDrawNode.kt:102)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:209)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performDraw(DelegatingLayoutNodeWrapper.kt:70)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:209)
        at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:82)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:209)
        at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:794)

**Comment by chrisbanes** [comment]
FYI, this is nothing to do with Horizontal/VerticalPager. It's just because Glide is extremely aggressive at recycling bitmaps (when it doesn't really need to).

I can't recreate this on any emulator and device I have and I don't really have the time to try and debug Glide. To be honest, I'm very close to deprecating and stopping development of the Glide library as it is causing too many issues.

**Comment by Fed93** [comment]
Thank you very much @chrisbanes! 
I've tried with Coil and it's working fine. I've associated the issue with Pager only because with normal list there are no problems of recycle!

So, i switch definitely to Coil and close the issue! 😄
