### ISSUE TITLE
[SwipeRefresh] Crash when scrolling

### ISSUE THREAD

**Issue by fornewid** [google/accompanist#428]
## Describe the bug
Crash when scrolling vertically in `SwipeRefresh`.

## To Reproduce
1. There is `SwipeRefresh` in the `HorizontalPager`.
2. Scrolls vertically.
4. Crash :sob:

```
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter <this>
        at androidx.compose.ui.input.nestedscroll.NestedScrollModifierKt.nestedScroll(Unknown Source:2)
        at androidx.compose.ui.input.nestedscroll.NestedScrollModifierKt.nestedScroll$default(NestedScrollModifier.kt:317)
        at com.google.accompanist.swiperefresh.SwipeRefreshKt.SwipeRefresh-Fsagccs(SwipeRefresh.kt:260)
        at com.google.accompanist.swiperefresh.SwipeRefreshKt$SwipeRefresh$3.invoke(Unknown Source:27)
        at com.google.accompanist.swiperefresh.SwipeRefreshKt$SwipeRefresh$3.invoke(Unknown Source:10)
        at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:96)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2139)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2402)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2554)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2525)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:555)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:733)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:102)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:443)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:415)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

## Screenshots?
> Tested on https://github.com/fornewid/Moop-Compose/pull/8.

https://user-images.githubusercontent.com/3405740/119001589-106ad780-b9c7-11eb-8380-274e9b3baa1a.mp4

## Environment:
 - Android OS version: Android 11
 - Device: Google Pixel 3a
 - Accompanist version: v0.10.0
 - Android Studio Bumblebee / Android Gradle Plugin 7.1.0-alpha01

**Comment by ch4rl3x** [comment]
Same here

## Environment:
Android OS version: Android 12
Device: Google Pixel 5
Compose version: 1.0.0-beta07
Accompanist version: v0.10.0
Android Studio Arctic Fox / Android Gradle Plugin 7.0.0-beta01

**Comment by Konyaco** [comment]
Same issue.

**Comment by chrisbanes** [comment]
Could someone provide some code which triggers this?

Just tried this and it's working as expected:

``` kotlin
HorizontalPager(
    state = rememberPagerState(pageCount = 10),
) {
    // Simulate a fake 2-second 'load'. Ideally this 'refreshing' value would
    // come from a ViewModel or similar
    var refreshing by remember { mutableStateOf(false) }
    LaunchedEffect(refreshing) {
        if (refreshing) {
            delay(2000)
            refreshing = false
        }
    }

    SwipeRefresh(
        state = rememberSwipeRefreshState(isRefreshing = refreshing),
        onRefresh = { refreshing = true },
    ) {
        LazyColumn(Modifier.fillMaxSize()) {
            items(20) {
                Text(
                    text = "Text",
                    Modifier.fillMaxWidth().padding(16.dp)
                )
            }
        }
    }
}
```

**Comment by fornewid** [comment]
> Tested on fornewid/Moop-Compose#8

If it's okay, can you check it out in the code above? :bow:

**Comment by fornewid** [comment]
I've written code to reproduce this error in accompanist's `sample` module.
To reproduce, I modified the code of `SwipeRefreshBasicSample.kt` as below.

Even without `Pager`,
if `SwipeRefresh` is split into a separate `composable` function and observe `LiveData` of `ViewModel`,
it will be reproduced immediately.

I also installed the `compose-runtime-livedata` library to use the official extension function.
```
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
```
```kt
package com.google.accompanist.sample.swiperefresh

import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.runtime.livedata.observeAsState
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewmodel.compose.viewModel

@Composable
private fun Sample() {
    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(stringResource(R.string.swiperefresh_title_basics)) },
                backgroundColor = MaterialTheme.colors.surface,
            )
        },
        modifier = Modifier.fillMaxSize()
    ) {
        val viewModel: SwipeRefreshViewModel = viewModel()
        val texts by viewModel.texts.observeAsState(emptyList())
        TextList(texts)
    }
}

@Composable
private fun TextList(texts: List<String>) {
    // Simulate a fake 2-second 'load'. Ideally this 'refreshing' value would
    // come from a ViewModel or similar
    var refreshing by remember { mutableStateOf(false) }
    LaunchedEffect(refreshing) {
        if (refreshing) {
            delay(2000)
            refreshing = false
        }
    }

    SwipeRefresh(
        state = rememberSwipeRefreshState(isRefreshing = refreshing),
        onRefresh = { refreshing = true },
    ) {
        LazyColumn {
            itemsIndexed(texts) { index, text ->
                Row(Modifier.padding(16.dp)) {
                    Image(
                        painter = rememberGlidePainter(randomSampleImageUrl(index)),
                        contentDescription = null,
                        modifier = Modifier.size(64.dp),
                    )

                    Spacer(Modifier.width(8.dp))

                    Text(
                        text = text,
                        style = MaterialTheme.typography.subtitle2,
                        modifier = Modifier
                            .weight(1f)
                            .align(Alignment.CenterVertically)
                    )
                }
            }
        }
    }
}

class SwipeRefreshViewModel : ViewModel() {
    private val _texts = MutableLiveData(List(20) { "Text" })
    val texts: LiveData<List<String>> get() = _texts
}
```

**Comment by chrisbanes** [comment]
I'm 99% sure that this is a Compose bug. Raised https://issuetracker.google.com/issues/188980714

**Comment by Tahazargar** [comment]
Thanks it was so impressive
