### ISSUE TITLE
[Glide] Build error w/ accompanist-glide:0.10.0 and compose beta07

### ISSUE THREAD

**Issue by newmanw** [google/accompanist#434]
## Describe the bug
Adding com.google.accompanist:accompanist-glide:0.10.0 throws the following exception when building

```
java.lang.IllegalStateException: function = <anonymous>, count = 3, index = 3
	at androidx.compose.compiler.plugins.kotlin.lower.ComposerLambdaMemoization.wrapFunctionExpression(ComposerLambdaMemoization.kt:671)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposerLambdaMemoization.visitComposableFunctionExpression(ComposerLambdaMemoization.kt:529)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposerLambdaMemoization.visitFunctionExpression(ComposerLambdaMemoization.kt:591)
```

Is com.google.accompanist:accompanist-glide:0.10.0  compatible with beta07?

## To Reproduce
Dependencies:
```
    implementation 'androidx.compose.ui:ui:1.0.0-beta07'
    implementation 'androidx.compose.ui:ui-tooling:1.0.0-beta07'
    implementation 'androidx.compose.foundation:foundation:1.0.0-beta07'
    implementation 'androidx.compose.material:material:1.0.0-beta07'
    implementation 'androidx.compose.material:material-icons-core:1.0.0-beta07'
    implementation 'androidx.compose.material:material-icons-extended:1.0.0-beta07'
    implementation 'androidx.activity:activity-compose:1.3.0-alpha08'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha05'
    implementation 'androidx.compose.runtime:runtime-livedata:1.0.0-beta07'
    implementation 'androidx.compose.runtime:runtime-rxjava2:1.0.0-beta07'

    implementation 'com.github.bumptech.glide:glide:4.12.0'
    implementation 'com.github.bumptech.glide:okhttp3-integration:4.12.0'
    implementation "com.google.accompanist:accompanist-glide:0.10.0"
    kapt 'com.github.bumptech.glide:compiler:4.12.0'
```

## Environment:
 - Android OS version: [e.g. Android 10.0]
 - Device: [Google Pixel 4]
 - Accompanist version: [e.g. v0.10]

**Comment by newmanw** [comment]
Seems this was an issue with either my gradle version or the compose kotlin compiler version.  Upgraded both, problem sovled.
