### ISSUE TITLE
[Insets] Crash when using windowsInsetsAnimationEnabled with R8 minified app

### ISSUE THREAD

**Issue by micHar** [google/accompanist#483]
## Describe the bug
App crashes when using `ProvideWindowInsets(windowInsetsAnimationsEnabled = true)` in a minified build on Android 11. Works for versions untouched by R8 and when `windowInsetsAnimationsEnabled = false`.

Stack trace: 

```
java.lang.AbstractMethodError: abstract method "android.view.WindowInsets android.view.WindowInsetsAnimation$Callback.onProgress(android.view.WindowInsets, java.util.List)"
        at android.view.View.dispatchWindowInsetsAnimationProgress(View.java:12131)
        at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:8457)
        at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:8463)
        at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:8463)
        at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:8463)
        at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:8463)
        at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:8463)
        at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:8463)
        at android.view.ViewRootInsetsControllerHost.dispatchWindowInsetsAnimationProgress(ViewRootInsetsControllerHost.java:111)
        at android.view.InsetsController.lambda$new$2$InsetsController(InsetsController.java:626)
        at android.view.-$$Lambda$InsetsController$zpmOxHfTFV_3me2u3C8YaXSUauQ.run(Unknown Source:2)
        at android.view.InsetsController.scheduleApplyChangeInsets(InsetsController.java:1493)
        at android.view.InsetsAnimationControlImpl.setInsetsAndAlpha(InsetsAnimationControlImpl.java:188)
        at android.view.InsetsAnimationControlImpl.setInsetsAndAlpha(InsetsAnimationControlImpl.java:172)
        at android.view.InsetsController$InternalAnimationControlListener.lambda$onReady$0$InsetsController$InternalAnimationControlListener(InsetsController.java:364)
        at android.view.-$$Lambda$InsetsController$InternalAnimationControlListener$SInf91MjJKDQFXwrp7C-HBi0xaQ.onAnimationUpdate(Unknown Source:13)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1566)
        at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:692)
        at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:655)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1087)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1106)
        at android.view.InsetsController$InternalAnimationControlListener.onReady(InsetsController.java:381)
        at android.view.InsetsController.lambda$startAnimation$6$InsetsController(InsetsController.java:1476)
        at android.view.-$$Lambda$InsetsController$VzAUS17blucBK1u6-37NlEpdYqI.run(Unknown Source:12)
        at android.view.ViewRootInsetsControllerHost$1.onPreDraw(ViewRootInsetsControllerHost.java:72)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1124)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3806)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2575)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9916)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
        at android.view.Choreographer.doCallbacks(Choreographer.java:809)
        at android.view.Choreographer.doFrame(Choreographer.java:744)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

## To Reproduce
1. Use `ProvideWindowInsets(windowInsetsAnimationsEnabled = true)`
2. Build app with`isMinifyEnabled = true` (and `isShrinkResources = true` ?).

## Expected behavior
No crash :)

## Environment:
 - Android OS version: Android 11 (works fine on 9).
 - Device: Samsung Galaxy S20+
 - Accompanist version: 0.11.1

## Additional context
Flutter had a similar bug, it's probably just some proguard rule thingy: https://github.com/flutter/flutter/issues/66232

**Comment by chrisbanes** [comment]
I've just tried a few different things to recreate this and it seems to be working fine with R8 enabled (tried both compat and full mode). Tried on emulators, Pixel 5 and a Samsung Z Fold 2.

Do you have access to a device which reproduces this issue?

**Comment by chrisbanes** [comment]
If so, can you try the following R8 rule?

```
-keepclassmembers class * extends android.view.WindowInsetsAnimation$Callback {
    public <methods>;
}
```

**Comment by micHar** [comment]
Yes, it crashes every time on my S20+, will try the rule, not sure if I can manage it today, though.

**Comment by chrisbanes** [comment]
There's no rush 👍. The setup is done, we just need to find the rule which works.

**Comment by micHar** [comment]
Tried both of them (separately), unfortunately both failed - still the same crash.

**Comment by chrisbanes** [comment]
Are you using R8 full mode?

**Comment by micHar** [comment]
No, just the usual stuff

```
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro")

```

I also tried to go the way flutter did and just `keep` everything from the package with class overriding the `WindowInsetsAnimation$Callback`, but that didn't work either.

```
-keep class com.google.accompanist.insets.** { *; }
```

**Comment by micHar** [comment]
Oh, I only just noticed that I was using using `compileSdk = 29` and `targetSdk = 29`. Changing both to 30 made it work!

But as far as I understand how `targetSdk` is designed to work, it should not crash this way, not sure if it's not an issue with `WindowInsetsAnimation`? It all worked with `compileSdk=29` and without R8 after all.

**Comment by chrisbanes** [comment]
I wonder if this is a desugaring issue or something? Does it work if you only change the compile sdk to 30? (So keep target sdk 29)

**Comment by micHar** [comment]
compileSdk=30 and targetSdk=29 works fine, no crash.

Then changed compileSdk to 29 just to be sure and it crashed again.

**Comment by chrisbanes** [comment]
Ah, this sounds like a R8 bug to me then.

**Comment by micHar** [comment]
Sure, I will report it there, thanks!
