### ISSUE TITLE
[Pager] Scrolling jumps around and app crashes when currentPageOffset is read

### ISSUE THREAD

**Issue by gpeal** [google/accompanist#485]
## Describe the bug
HorizontalPager works great until you read `pagerState.currentPageOffset`. Once you access it, it causes the scrolling behavior to become erratic. It snaps on drags and flings and eventually crashes with:
```
java.lang.NullPointerException
	at com.google.accompanist.pager.PagerState.setCurrentLayoutPageOffset(PagerState.kt:704)
	at com.google.accompanist.pager.PagerState.snapToPage(PagerState.kt:342)
	at com.google.accompanist.pager.PagerState.snapToPage$default(PagerState.kt:333)
	at com.google.accompanist.pager.PagerState.snapToNearestPage(PagerState.kt:350)
	at com.google.accompanist.pager.PagerState.fling$pager_release(PagerState.kt:604)
	at com.google.accompanist.pager.PagerState$fling$1.invokeSuspend(Unknown Source:18)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

## To Reproduce
1. Run the attached sample project ([AccompanistPagerBug.zip](https://github.com/google/accompanist/files/6643418/AccompanistPagerBug.zip))
2. Scroll around and notice erratic behavior
3. Comment out the `Text` composable
4. Notice that scrolling is now smooth

## Screenshots?
https://user-images.githubusercontent.com/1307745/121798264-23458600-cbda-11eb-946f-d9372b94b3ef.mp4

## Environment:
 - Android OS version: 30
 - Device: Emulat9r
 - Accompanist version: 0.11.1

**Comment by chrisbanes** [comment]
The performance thing isn't a Pager thing: you're observing state and printing it, so this is a general Compose performance issue. 

I'll take a look at the crash.

**Comment by gpeal** [comment]
@chrisbanes I originally discovered this by trying to map the pager state to the progress of a Lottie animation and it had the same behavior. Interestingly, if I nest the Text one level by wrapping it in its own Composable then the issue goes away. This makes me think that the issue happens when HorizontalPager recomoposes on every offset change and explains why it doesn't happen to HorizontalPagerIndicator.

**Comment by chrisbanes** [comment]
> This makes me think that the issue happens when HorizontalPager recomoposes on every offset change and explains why it doesn't happen to HorizontalPagerIndicator.

That's exactly what your `Text` code is doing. It's performing the state read in the `Box` content block, and therefore that whole block needs to be recomposed when on each value change. 

Extracting the state read out to another function means that only that function will need to be recomposed, which is exactly what the indicators do.

**Comment by chrisbanes** [comment]
Note, there ways to throttle which you can throttle the state changes. Something like this:

```
// Will round (and throttle) offset changes to the nearest 0.01f (1%)
val throttledOffset by remember {
    derivedStateOf {
        (pagerState.currentPageOffset * 100).roundToInt() / 100f
    }
}
```
