### ISSUE TITLE
Getting crash on Android 8.0

### ISSUE THREAD

**Issue by Deepika-PFJ** [google/accompanist#495]
## Describe the bug
rememberCoilPainter  is crashing on android 8.0. 
`FATAL EXCEPTION: main
    Process: com.pilottravelcenters.mypilot.dev, PID: 21569
    java.lang.IllegalStateException: Invalid resource ID: 2131230944
        at coil.util.-Contexts.getDrawableCompat(Contexts.kt:28)
        at coil.util.-Requests.getDrawableCompat(Requests.kt:24)
        at coil.request.ImageRequest.getError(ImageRequest.kt:151)
        at coil.memory.RequestService.errorResult(RequestService.kt:27)
        at coil.RealImageLoader.executeMain(RealImageLoader.kt:193)
        at coil.RealImageLoader$execute$2.invokeSuspend(RealImageLoader.kt:134)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:349)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:27)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:171)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at coil.RealImageLoader.execute(RealImageLoader.kt:133)
        at com.google.accompanist.coil.CoilLoader$load$1.invokeSuspend(Coil.kt:176)
        at com.google.accompanist.coil.CoilLoader$load$1.invoke(Unknown Source:8)
        at com.google.accompanist.coil.CoilLoader$load$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo$suspendImpl(Builders.kt:344)
        at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo(Unknown Source:0)
        at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)`

## To Reproduce
I used below code snippet
`Image(
        painter = rememberCoilPainter(
            request = ImageRequest.Builder(LocalContext.current)
                .data(imageUrl)
                .placeholder(R.drawable.ic_default)
                .error(R.drawable.ic_default)
                .fallback(R.drawable.ic_default)
                .build()
        ),
        modifier = Modifier
            .requiredSize(80.dp),
        contentDescription = stringResource(id = R.string.icon)
    )`

## Environment:
 - Android OS version: 8.0
 - Device: Motorola Z2 play
 - Accompanist version: 0.10.0

## Additional context
This is working fine on later versions but crashing on 8.0.

**Comment by chrisbanes** [comment]
That's a Coil crash, so please raise it on the Coil issue tracker: https://github.com/coil-kt/coil

Having a quick look at the stack trace: `java.lang.IllegalStateException: Invalid resource ID: 2131230944`. There's something wrong with either that drawable, or your build.
