### ISSUE TITLE
[ImageLoading] java.lang.NoSuchFieldError when fadeIn = true

### ISSUE THREAD

**Issue by ashar-7** [google/accompanist#504]
## Describe the bug
```
java.lang.NoSuchFieldError: No field $stable of type I in class Landroidx/compose/animation/core/Transition; or its superclasses (declaration of 'androidx.compose.animation.core.Transition' appears in /data/app/~~dVxvAmSM_OsW1_tgG-PP9g==/com.myapp-U5JFTl9WJkrfgXs5b-seZQ==/base.apk)
        at com.google.accompanist.imageloading.MaterialLoadingImage.updateFadeInTransition(MaterialLoadingImage.kt:53)
        at com.google.accompanist.imageloading.LoadPainterKt.animateFadeInColorFilter(LoadPainter.kt:382)
        at com.google.accompanist.imageloading.LoadPainterKt.rememberLoadPainter(LoadPainter.kt:119)
        at com.google.accompanist.glide.GlideKt.rememberGlidePainter(Glide.kt:108)
```
I get this error in `v0.12.0` when fadeIn is set to true. Works fine when fadeIn is false. Happens both in Glide and Coil.

## Environment:
 - Android OS version: Android 11
 - Device: Emulator, Google Pixel 5
 - Accompanist version: v0.12.0

**Comment by chrisbanes** [comment]
I’m guessing that you’re not using Compose 1.0.0-beta09? Each release is built for a specific version of Compose, and it is listed on the relevant release.

**Comment by ashar-7** [comment]
I am using beta09. I'll check for any transitive dependencies if that helps?

**Comment by ashar-7** [comment]
My bad, I wasn't using buildSrc's compose version in a module
