### ISSUE TITLE
[Navigation-Material] Crash when using ModalBottomSheetLayout with Scaffold

### ISSUE THREAD

**Issue by CurtJRees** [google/accompanist#611]
## Describe the bug
When attempting to use ModalBottomSheetLayout with Scaffold, I'm getting this exception which in turn causes a crash
```
java.lang.IllegalStateException: You cannot access the Navigator's state until the Navigator is attached
        at androidx.navigation.Navigator.getState(Navigator.kt:68)
        at com.google.accompanist.navigation.material.BottomSheetNavigator.access$getState(BottomSheetNavigator.kt:102)
        at com.google.accompanist.navigation.material.BottomSheetNavigator$sheetContent$1.invoke(BottomSheetNavigator.kt:121)
        at com.google.accompanist.navigation.material.BottomSheetNavigator$sheetContent$1.invoke(BottomSheetNavigator.kt:118)
```

## To Reproduce
Took the sample and wrapped the NavHost inside ModalBottomSheetLayout with a Scaffold
```
@Composable
fun BottomSheetNavDemo() {
    val navController = rememberNavController()
    val bottomSheetNavigator = rememberBottomSheetNavigator()
    navController.navigatorProvider += bottomSheetNavigator

    ModalBottomSheetLayout(bottomSheetNavigator) {
        Scaffold(
            content = { _ ->
                NavHost(navController, Destinations.Home) {
                    composable(Destinations.Home) {
                        HomeScreen(
                            showSheet = {
                                navController.navigate(Destinations.Sheet + "?arg=From Home Screen")
                            },
                            showFeed = { navController.navigate(Destinations.Feed) }
                        )
                    }
                    composable(Destinations.Feed) { Text("Feed!") }
                    bottomSheet(Destinations.Sheet + "?arg={arg}") { backstackEntry ->
                        val arg = backstackEntry.arguments?.getString("arg") ?: "Missing argument :("
                        BottomSheet(
                            showFeed = { navController.navigate(Destinations.Feed) },
                            showAnotherSheet = {
                                navController.navigate(Destinations.Sheet + "?arg=${UUID.randomUUID()}")
                            },
                            arg = arg
                        )
                    }
                }
            },
            bottomBar = {
                Box(Modifier.fillMaxWidth().height(56.dp).background(Color.Red))
            }
        )
    }
}
```

## Expected behavior
No crash, Bottom sheet to be shown over any bottom bar from the Scaffold

## Environment:
 - Android OS version: Android 12
 - Device: Google Pixel 4XL
 - Accompanist version: 0.16.0

**Comment by jossiwolf** [comment]
@ianhanniballake looks like we try to access the navigator's state too early here. I'm thinking of just bringing the `attached` check back, what do you think?

**Comment by ianhanniballake** [comment]
> @ianhanniballake looks like we try to access the navigator's state too early here. I'm thinking of just bringing the `attached` check back, what do you think?

Seems reasonable to me.
