### ISSUE TITLE
Pager bugged in version 0.16.0

### ISSUE THREAD

**Issue by Guimareshh** [google/accompanist#616]
## Describe the bug
Bump my app from Accompanist `0.15.0` to `0.16.0` and my pager isn't visible anymore and while doing a `animateScrollToPage(index)` the app crash with a NPE

## Screenshots?
Here is a Gif showing the issue in the first part, the second part is the same app but with Accompanist version ` 0.15.0`

![20210806-215155](https://user-images.githubusercontent.com/9654353/128571508-704a1a3e-064a-473a-a301-e89f59ea0f24.gif)

## Environment:
 - Android OS version: Tested with Android API 27+
 - Device: Issue is on any emulator I tested and my Pixel 3
 - Accompanist version: 0.16.0

## Additional context
The code snippet of this view:
````kotlin
@Composable
fun HikesOnMapScreen(viewModel: HikesOnMapViewModel) {

    val hikeMarkerList by viewModel.hikesOnMapListState.collectAsState(initial = emptyList())
    val pagerState = rememberPagerState(pageCount = hikeMarkerList.size, initialOffscreenLimit = 2)

    LaunchedEffect(pagerState) {
        snapshotFlow { pagerState.currentPage }.collect { page ->
            viewModel.updateSelectedHikeOnMapCard(page)
        }
    }
    LaunchedEffect(pagerState) {
        viewModel.selectedHikeIndex.collect { index ->
            pagerState.animateScrollToPage(index)
        }
    }

    BoxWithConstraints {
        MapViewWithMarkerContainer()
        TopAppBar()
        HorizontalPager(
            state = pagerState,
            modifier = Modifier
                .align(Alignment.BottomCenter)
                .fillMaxWidth()
                .navigationBarsPadding()
                .padding(bottom = 32.dp),
            itemSpacing = 8.dp,
        ) { page ->
            val hikeOnMapCard = hikeMarkerList[page]
            HikeOnMapCard(hikeOnMapCard) {
                viewModel.hikeOnMapCardClicked(hikeOnMapCard.id)
            }
        }
    }
}

````

**Comment by chrisbanes** [comment]
Can you please post the exception + stack trace?

**Comment by Guimareshh** [comment]
Here is the stack trace of the NullPointerException when doing a `animateScrollToPage(index)`

```
2021-08-09 13:15:59.160 E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NullPointerException
        at com.google.accompanist.pager.PagerState$animateScrollToPage$2.invokeSuspend(PagerState.kt:713)
        at com.google.accompanist.pager.PagerState$animateScrollToPage$2.invoke(Unknown Source:8)
        at com.google.accompanist.pager.PagerState$animateScrollToPage$2.invoke(Unknown Source:4)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invokeSuspend(ScrollableState.kt:147)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invoke(Unknown Source:8)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invoke(Unknown Source:4)
        at androidx.compose.foundation.MutatorMutex$mutateWith$2.invokeSuspend(MutatorMutex.kt:160)
        at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke(Unknown Source:8)
        at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
        at androidx.compose.foundation.MutatorMutex.mutateWith(MutatorMutex.kt:153)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invokeSuspend(ScrollableState.kt:145)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invoke(Unknown Source:8)
        at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
        at androidx.compose.foundation.gestures.DefaultScrollableState.scroll(ScrollableState.kt:144)
        at com.google.accompanist.pager.PagerState.scroll(PagerState.kt:625)
        at androidx.compose.foundation.gestures.ScrollableState$DefaultImpls.scroll$default(ScrollableState.kt:51)
        at com.google.accompanist.pager.PagerState.animateScrollToPage(PagerState.kt:285)
        at com.google.accompanist.pager.PagerState.animateScrollToPage$default(PagerState.kt:272)
        at com.hika.hikesOnMap.ui.HikesOnMapScreenKt$HikesOnMapScreen$3$invokeSuspend$$inlined$collect$1.emit(Collect.kt:135)
        at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:398)
        at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by chrisbanes** [comment]
Hmmm, the only relevant PR which could cause this is #588. Is the sample app public anywhere?

**Comment by chrisbanes** [comment]
Don't worry, found the issue (I think)

**Comment by Guimareshh** [comment]
>Hmmm, the only relevant PR which could cause this is #588. Is the sample app public anywhere?

Sorry it's a private repo 😕 

>Don't worry, found the issue (I think)

Thanks for the fix! Is there a snapshot version published every PR merged ? I will be able to test if it's working fine with the fix!

**Comment by Guimareshh** [comment]
Just tried version 0.16.1, it's working perfectly! Thanks for the fix 🙏

**Comment by chrisbanes** [comment]
No problem, thanks for confirming!
