### ISSUE TITLE
Activity SupportActionBar is null

### ISSUE THREAD

**Issue by christinetrinh** [google/accompanist#709]
When trying to get the supportActionBar for an Activity from within a fragment the supportActionBar is null. Is this expected behavior? We're using this to change theme colors.  

Stacktrace:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dataforma.dflowslope.android/com.dataforma.dflowslope.android.activity.navHost.NavHostActivity}: android.view.InflateException: Binary XML file line #28 in com.dataforma.dflowslope.android:layout/navhost_drawer_layout: Binary XML file line #28 in com.dataforma.dflowslope.android:layout/navhost_drawer_layout: Error inflating class fragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3995)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8587)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: android.view.InflateException: Binary XML file line #28 in com.dataforma.dflowslope.android:layout/navhost_drawer_layout: Binary XML file line #28 in com.dataforma.dflowslope.android:layout/navhost_drawer_layout: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #28 in com.dataforma.dflowslope.android:layout/navhost_drawer_layout: Error inflating class fragment
     Caused by: java.lang.NullPointerException
        at com.dataforma.dflowslope.android.module.base.fragment.BaseNavHostFragment.changeFragmentTheme(BaseNavHostFragment.kt:40)`

line 40 (parent is the Activity of the fragment):
`                parent.supportActionBar!!.setBackgroundDrawable(ColorDrawable(resources.getColor(lightColor, parent.theme)))
`

**Comment by chrisbanes** [comment]
Not related to Accompanist.
