### ISSUE TITLE
AnimatedNavHost Crashed in Compose v1.1.0-alpha05

### ISSUE THREAD

**Issue by jakode2020** [google/accompanist#773]
### It seems that a series of animations have changed in the new version

jetpack compose = 1.1.0-alpha05
accompanist = 0.19.0
kotlin = 1.5.31
sdk = 31

```
stack=java.lang.NoSuchMethodError: No static method fadeIn$default(FLandroidx/compose/animation/core/FiniteAnimationSpec;ILjava/lang/Object;)Landroidx/compose/animation/EnterTransition; in class Landroidx/compose/animation/EnterExitTransitionKt; or its super classes (declaration of 'androidx.compose.animation.EnterExitTransitionKt' appears in /data/app/com.itdm.digiplus-2/base.apk)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$1.invoke(AnimatedNavHost.kt:84)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$1.invoke(AnimatedNavHost.kt:84)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$finalEnter$1$1.invoke(AnimatedNavHost.kt:201)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$finalEnter$1$1.invoke(AnimatedNavHost.kt:173)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$7$1.invoke(AnimatedNavHost.kt:244)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$7$1.invoke(AnimatedNavHost.kt:244)
        at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:650)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:242)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:91)
        at com.itdm.digiplus.ui.navigation.NavigationKt$Navigation$2$1$2.invoke(Navigation.kt:78)
        at com.itdm.digiplus.ui.navigation.NavigationKt$Navigation$2$1$2.invoke(Navigation.kt:77)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:316)
        at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:314)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2$1$1.invoke(SubcomposeLayout.kt:244)
        at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2$1$1.invoke(SubcomposeLayout.kt:244)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:3341)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2586)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2575)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(SnapshotState.kt:563)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2575)
        at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:2526)
        at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:478)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:727)
        at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:2991)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:433)
        at androidx.compose.ui.layout.SubcomposeLayoutState.subcomposeInto(SubcomposeLayout.kt:262)
        at androidx.compose.ui.layout.SubcomposeLayoutState.access$subcomposeInto(SubcomposeLayout.kt:148)
        at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2.invoke(SubcomposeLayout.kt:237)
        at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2.invoke(SubcomposeLayout.kt:234)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.withNoObservations(SnapshotStateObserver.kt:142)
        at androidx.compose.ui.node.OwnerSnapshotObserver.withNoSnapshotReadObservation$ui_release(OwnerSnapshotObserver.kt:55)
    	at andr
```

**Comment by ianhanniballake** [comment]
As per the [Compose Animation `1.0.0-alpha05` release notes](https://developer.android.com/jetpack/androidx/releases/compose-animation#1.1.0-alpha05), that release did have breaking changes that mean that any library built against Compose 1.0.3 (like Accompanist 0.19.0) that uses the transition APIs will be broken.

These APIs were all technically experimental, so breaking changes like this were always a possibility, but it means this can't be resolved until Accompanist switches to depend on Compose 1.1 (which, in turn forces all consumers of that library to depend on Compose 1.1).

Moving to depend on Compose 1.1 was already on our radar, but this is definitely a concrete use case that _requires_ it. We'll prioritize that move.

**Comment by jakode2020** [comment]
> As per the [Compose Animation `1.0.0-alpha05` release notes](https://developer.android.com/jetpack/androidx/releases/compose-animation#1.1.0-alpha05), that release did have breaking changes that mean that any library built against Compose 1.0.3 (like Accompanist 0.19.0) that uses the transition APIs will be broken.
> 
> These APIs were all technically experimental, so breaking changes like this were always a possibility, but it means this can't be resolved until Accompanist switches to depend on Compose 1.1 (which, in turn forces all consumers of that library to depend on Compose 1.1).
> 
> Moving to depend on Compose 1.1 was already on our radar, but this is definitely a concrete use case that _requires_ it. We'll prioritize that move.

Thanks for pointing me to this. I also tried something and set the AnimatedNavHost function like this. 
```
AnimatedNavHost(
    navController = navController,
    startDestination = "route",
    enterTransition = { _, _ -> fadeIn(animationSpec = tween(700)) },
    exitTransition = { _, _ -> fadeOut(animationSpec = tween(700)) },
) {
}
```
The result was that the program was working, but moving the pages and running the fade animation was heavy and stuck.
