### ISSUE TITLE
"Page must be 0 when pageCount is 0" thrown when pageCount > 0

### ISSUE THREAD

**Issue by zoltish** [google/accompanist#859]
## Describe the bug
Scrolling through a HorizontalPager throws this exception in rare cases, Ive seen 3 crash logs in a group of about 1000 users. The pager always shows a fixed list that never changes. I _believe_ the issue is triggered by recompositions happening while scrolling the pager. 

## Environment:
 - Android OS version: [Android 7 & 9]
 - Device: [Emulated Nexus 5 & Huawei P10]
 - Accompanist version: [0.21.1-beta]

**Comment by cristianbtg** [comment]
I saw this happening starting v0.19.0 when a configuration change happened (e.g. language) where during recomposition the `pageCount` and `currentPage` were set to 0, even though I was using the `rememberPagerState()`. 

Before v0.19.0 `PagerState.Saver` was saving `pageCount` and `currentPage` and it was working fine; currently it's only saving `pageCount`, but from my observation, during the first recomposition it's 0 so it might lead to some crashes.

**Comment by aazizbekyan** [comment]
The workaround for time being:

```
    LaunchedEffect(pagerState.pageCount) {
        if (pagerState.pageCount != 0) {
             // now interact with pagerState
        }
    }
```

**Comment by andkulikov** [comment]
Can you show the crash stacktrace?

**Comment by zoltish** [comment]
Sorry, Ive switched crash reporting tools since my post and I no longer have access to it. I guess the good news is that I havent seen it since then in a group of 5000 users. Ill let you know if it pops up again!

**Comment by yschimke** [comment]
I've hit a tangential bug.

I can define initialPage to either of my two pages.

```
    val pagerState = rememberPagerState(initialPage = 0)
```

If in a launched effect I want to update the initial page or scroll to a page, then I can only do that once the composable has rendered.  Which would be the scrollToPage case.  

This means I can update the initial page once by launched effect completes.

**Comment by yschimke** [comment]
Never mind, I think I can just move my LaunchedEffect inside to where I have already created the HorizontalPager.

**Comment by yasandev** [comment]
This is the most common crash on my Compose app, I just started handling it by just checking the page count.

@andkulikov I use Firebase Crashlytics so I do have the crash log:

> Fatal Exception: java.lang.IllegalArgumentException: page must be 0 when pageCount is 0
       at com.google.accompanist.pager.PagerState.requireCurrentPage(PagerState.java:1)
       at com.google.accompanist.pager.PagerState.animateScrollToPage$default(PagerState.java:26)
       at yasan.space.mnml.ai.launcher.ui.main.MainActivity$HandleGlobalEvents$1$1.invokeSuspend(MainActivity.java:26)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:2)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:86)
       at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.java:1)
       at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.java:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7864)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

> arch_disk_io_0
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

> pool-4-thread-1
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1120)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:849)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

> pool-14-thread-1
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

I can send the rest if you want as well.

**Comment by dbobrzyk** [comment]
@andkulikov PagerState also crashes on version accompanist = "0.17.0"

`Fatal Exception: java.lang.IllegalArgumentException
page must be 0 when pageCount is 0
com.google.accompanist.pager.PagerState.requireCurrentPage (PagerState.kt:656)
com.google.accompanist.pager.PagerState.updateLayoutPages (PagerState.kt:486)
com.google.accompanist.pager.PagerState.setPageCount (PagerState.java:221)
com.google.accompanist.pager.PagerStateKt.rememberPagerState (PagerState.kt:81)`

**Comment by andkulikov** [comment]
> @andkulikov PagerState also crashes on version accompanist = "0.17.0"
Please try to upgrade to the latest version before reporting any bugs - https://github.com/google/accompanist/releases

**Comment by yasandev** [comment]
> I cant Solve it . Any Solution !!

Just check the page size before changing the current page:

` if (pagerState.pageCount != 0) pagerState.animateScrollToPage(MyPages.TargetPage)`

**Comment by dbobrzyk** [comment]
> @dbobrzyk
> 
> Please try to upgrade to the latest version before reporting any bugs - https://github.com/google/accompanist/releases

After updating to 0.23.0 version, issue is still present.

**Comment by wakaztahir** [comment]
reopen !

**Comment by arbyruns** [comment]
I was able to solve this by adding `state = pagerState` to `HorizontalPager`. So something like this 

```
val pagerState = rememberPagerState()

HorizontalPager(count = 10, state = pagerState) { page ->
...
}
```

**Comment by undermark5** [comment]
@arbyruns This was fixed by https://github.com/google/accompanist/pull/1195, which is included as of https://github.com/google/accompanist/releases/tag/v0.24.11-rc. If you can update the library, to anything newer than that this is no longer an isse.
