### ISSUE TITLE
Accompanist is crashing  java.lang.NoSuchMethodError: No static method rememberPagerState on Release

### ISSUE THREAD

**Issue by jibraniqbal-careem** [google/accompanist#878]
## Describe the bug
Accompanist is crashing the minified proguard app in release version 0.20.0 using compose version 1.0.5.
 
## To Reproduce
1. Import Accompanist
2. Create a minified r8/proguard release
3. Open the app

## Expected behavior
It Shouldn't crash.

## Environment:
 - Android OS version: API 30
 - Device: Emulator
 - Accompanist version: 0.20.0

## Additional context
StackTrace

```
Process: com.careem.acma.qa, PID: 5393
    java.lang.NoSuchMethodError: No static method rememberPagerState(IIFIZLe1/i;II)Ls51/g; in class Ls51/i; or its super classes (declaration of 's51.i' appears in /data/app/com.example.qa-EMuA8-jvfzLacCR6fzoRFA==/base.apk!classes4.dex)
        at kz0.b.a(:41)
        at kz0.b$e.a(Unknown Source:9)
        at kz0.b$e.invoke(Unknown Source:9)
        at e1.z0.g(:140)
        at e1.j.J0(:2158)
        at e1.j.g(:2404)
        at e1.j$h.invoke(:2585)
        at e1.j$h.invoke(:2571)
        at e1.o1.c(:234)
        at e1.n1.i(:1)
        at e1.j.i0(:2571)
        at e1.j.I0(:2547)
        at e1.o.b(:620)
        at e1.a1.W(:786)
        at e1.a1.D(:105)
        at e1.a1$j$a.a(:456)
        at e1.a1$j$a.invoke(:425)
        at androidx.compose.ui.platform.f0$c.doFrame(:34)
        at androidx.compose.ui.platform.d0.P1(:109)
        at androidx.compose.ui.platform.d0.J1(:41)
        at androidx.compose.ui.platform.d0$d.doFrame(:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by dmitrytavpeko** [comment]
According to release notes of the Accompanist you need to use [0.20.2](https://github.com/google/accompanist/releases/tag/v0.20.2) which is compatible with Compose 1.0.5. 
Did you try to use 0.20.2?

**Comment by jibraniqbal-careem** [comment]
Yes we tried it as well. :(

**Comment by PierreVieira** [comment]
I'm getting the same crash. If you put the library in the recommended version (`0.20.2`) the error keeps happening. I'm using compose in version `1.0.5`.

**Comment by andkulikov** [comment]
It would be nice if someone can share the project where it is reproducible (if you don't want to share it publicly you can send it to my email andreykulikov@google.com) as I tried to use rememberPagerState with Compose 1.0.5 and Accompanist 0.20.2 in my sample project and it is not crashing in the release build.

**Comment by PierreVieira** [comment]
> It would be nice if someone can share the project where it is reproducible (if you don't want to share it publicly you can send it to my email [andreykulikov@google.com](mailto:andreykulikov@google.com)) as I tried to use rememberPagerState with Compose 1.0.5 and Accompanist 0.20.2 in my sample project and it is not crashing in the release build.

@andkulikov 
I got confused with stacktrace. The stacktrace I was getting was related to another error, but it had the same exception:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.studiosol.dojo.compose, PID: 20098
    java.lang.NoSuchMethodError: No static method AnimatedContent(Landroidx/compose/animation/core/Transition;Landroidx/compose/ui/Modifier;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Alignment;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/animation/AnimatedContentKt; or its super classes (declaration of 'androidx.compose.animation.AnimatedContentKt' appears in /data/app/com.studiosol.dojo.compose-3MdDmITAsMaDnU7SsR3Ocw==/base.apk)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:242)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:91)
        at com.studiosol.dojo.compose.presentation.MainActivity$onCreate$1$1$1.invoke(MainActivity.kt:42)
        at com.studiosol.dojo.compose.presentation.MainActivity$onCreate$1$1$1.invoke(MainActivity.kt:40)
...
```
In this case I managed to solve this by putting compose in version `1.1.0-beta03` and accompanist in version `0.21.3-beta`. Thanks!

**Comment by PierreVieira** [comment]
@jibraniqbal-careem
@dmitrytavpeko 
Your case should be similar to mine, I recommend checking all dependencies related to compose and accompanist and see if they are following the same version. In my case, as I said, I put all that needed compose in version `1.1.0-beta03` and in the case of accompanist in version `0.21.3-beta`

**Comment by andkulikov** [comment]
I will close it for now. As mentioned already it could be some strange incompatibility between libraries
