### ISSUE TITLE
Crashes with nested Nav Graph

### ISSUE THREAD

**Issue by shawnthye** [google/accompanist#879]
## Describe the bug

I have a question, is it ok to have nested NavHost?

I have the Root NavHost for `ModalDrawer`, Child NavHost for `BottomNavigation`

So when I am trying to disable the animation, I got crash when back the to Home of `Drawer NavHost`

It worked if keep the default animation, or the default Compose's NavHost

```
@ExperimentalAnimationApi
@Composable
fun PlaygroundNavGraph(
    ...
) {
    AnimatedNavHost(
        navController = navController,
        startDestination = startDestination.route,
        enterTransition = { EnterTransition.None },
        exitTransition = { ExitTransition.None },
        popEnterTransition = { EnterTransition.None },
        popExitTransition = { ExitTransition.None },
    ) {
        composable(PlaygroundDestination.Home.route) {
            Home(openDrawer = openDrawer)
        }

        navigation(
            route = PlaygroundDestination.ProductHunt.route,
            startDestination = Screen.Discover.route,
        ) {
            composable(Screen.Discover.route) {
                ProductHunt(openDrawer = openDrawer) // inside here has another AnimatedNavHost
            }
        }
    }
}
```

Already upgrade to the latest beta for both `Compose` and `Accompanist`

**Reproduce repo** https://github.com/shawnthye/playground/tree/animated-nav-host

## To Reproduce
1. Go to 'Gallery' via ModalDrawer
2. Click on 'Any Tab on Bottom Navigation'
3. Press device back button until Home

```
2021-11-19 07:33:16.125 app.playground.internal E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.playground.internal, PID: 13455
    java.lang.IllegalStateException: You cannot access the NavBackStackEntry's ViewModels until it is added to the NavController's back stack (i.e., the Lifecycle of the NavBackStackEntry reaches the CREATED state).
        at androidx.navigation.NavBackStackEntry.getViewModelStore(NavBackStackEntry.kt:180)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:149)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:91)
        at feature.playground.producthunt.ProductHuntNavGraphKt.ProductHuntNavGraph(ProductHuntNavGraph.kt:52)
        at feature.playground.producthunt.ProductHuntKt$ProductHunt$2.invoke(ProductHunt.kt:78)
        at feature.playground.producthunt.ProductHuntKt$ProductHunt$2.invoke(ProductHunt.kt:77)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
        at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
        at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:140)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2158)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2404)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2585)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2571)
        at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:234)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2571)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2547)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:620)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:786)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:105)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:456)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:425)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

## Expected behavior
Should not crash?

## Screenshots?
N/A

## Environment:
 - Android OS version: API 30
 - Device: Emulator, Google Pixel 4
 - Accompanist version: 0.21.2-beta
 - Compose version: 1.1.0-beta03

## Additional context
N/A

**Comment by shawnthye** [comment]
Update, setting the minimal like below doesn't crash

```
    AnimatedNavHost(
        navController = navController,
        startDestination = startDestination.route,
        enterTransition = { fadeIn(animationSpec = tween(1)) },
        exitTransition = { fadeOut(animationSpec = tween(1)) },
        popEnterTransition = { fadeIn(animationSpec = tween(1)) },
        popExitTransition = { fadeOut(animationSpec = tween(1)) },
    ) {
    }
```

**Comment by shawnthye** [comment]
Found the issue, it because the route conflict I believe
