### ISSUE TITLE
The following problem occurred when I used the launchPermissionRequest method

### ISSUE THREAD

**Issue by wjbd** [google/accompanist#896]
java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
        at androidx.fragment.app.FragmentActivity.checkForValidRequestCode(FragmentActivity.java:714)
        at androidx.fragment.app.FragmentActivity.validateRequestPermissionsRequestCode(FragmentActivity.java:729)
        at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:516)
        at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:197)
        at androidx.activity.result.ActivityResultRegistry$3.launch(ActivityResultRegistry.java:243)
        at androidx.activity.compose.ActivityResultLauncherHolder.launch(ActivityResultRegistry.kt:154)
        at androidx.activity.compose.ManagedActivityResultLauncher.launch(ActivityResultRegistry.kt:143)
        at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
        at com.google.accompanist.permissions.MutablePermissionState.launchPermissionRequest(MutablePermissionState.kt:102)

launchPermissionRequest method i use in launchedEffect

**Comment by ianhanniballake** [comment]
The Activity Result APIs require that you use Fragment 1.3.0 or higher as per [their original release notes](https://developer.android.com/jetpack/androidx/releases/activity#1.2.0). This error only occurs when you're using an old version of Fragments. You need to upgrade either your direct dependency on Fragments or on libraries like AppCompat that pull in a dependency on Fragments (use AppCompat 1.3.1 or higher).

Note that Compose itself (nor the Activity Result APIs) do not require that you use `FragmentActivity` - using `ComponentActivity` directly is perfectly acceptable for a Compose only app. (You would only need `FragmentActivity` if you are using Fragments and `AppCompatActivity` (from AppCompat 1.3.0 or higher) if you are still using Views).
